### ISSUE TITLE
vSphere VCSA 7.0 VCPG-70-000005 and VCPG-70-000012

### ISSUE THREAD

**Issue by pstearns** [vmware/dod-compliance-and-automation#101]
### Describe the bug

VCPG-70-000005 and VCPG-70-000012
VMware Postgres must enforce authorized access using the users group, however they are set to vpgmongrp not users. 
The vpgmongrp seems to be a more restrictive group which should satisfy the STIG item. 

### Reproduction steps

#VCPG-70-000005
Check Text: At the command prompt, enter the following command:
find /var/log/vmware/vpostgres/* -xdev -type f -a '(' -not -perm 600 -o -not -user vpostgres -o -not -group users ')' -exec ls -ld {} \;

If any files are returned, this is a finding.

Output:
Returns group permissions with vpgmongrp. 

#VCPG-70-000012
Check Text: At the command prompt, execute the following command:
stat -c "%a:%U:%G" /storage/db/vpostgres_ssl/server.key

Output:
Also returns the vpgmongrp instead of users group. 

### Expected behavior

STIG expects permissions set to vpostgres:users
Update check to be users or vpgmongrp groups.

**Comment by rlakey** [comment]
Fixed by #104
