### ISSUE TITLE
Ansible: PHTN-30-000057 overwrites PHTN-30-000014

### ISSUE THREAD

**Issue by pstearns** [vmware/dod-compliance-and-automation#102]
### Describe the bug

PHTN-30-000014 task adds line:  "space_left_action = SYSLOG" 
PHTN-30-000057 task regex: regexp: '^space_left.*$' overwrites the "space_left_action = SYSLOG" lines in Auditd.conf file. 

### Reproduction steps

Running Ansible Task PHTN-30-000057

Original Tasks:
- name: PHTN-30-000057 - Configure auditd space_left
  ansible.builtin.lineinfile:
    dest: '{{ var_auditd_conf_file }}'
    regexp: '^space_left.*$'

- name: PHTN-30-000014 - Configure auditd space_left_action
  ansible.builtin.lineinfile:
    dest: '{{ var_auditd_conf_file }}'
    regexp: '^space_left_action.*$'

### Expected behavior

Adding a space to PHTN-30-000057 regex removes the conflict. 
Suggested Update:
- name: PHTN-30-000057 - Configure auditd space_left
  ansible.builtin.lineinfile:
    dest: '{{ var_auditd_conf_file }}'
    regexp: '^space_left  .*$'

**Comment by rlakey** [comment]
Good catch. Added a \s to look for the space.
