### ISSUE TITLE
Ansible: sysctl reload and auditd restart issues

### ISSUE THREAD

**Issue by pstearns** [vmware/dod-compliance-and-automation#103]
### Describe the bug

Ansible tasks that reload sysctl when ipv6 is disabled fail. 
and
The restart auditd handler is inconsitent in restarting auditd service. 

### Reproduction steps

#reload sysctl
Example PHTN-30-000101 
ipv6 is disabled and the check is open
When ansible.posix.sysctl runs to reload sysctl the follow error is produced:
fatal: [server]: FAILED! => {"changed": false, "msg": "Failed to reload sysctl: net.ipv6.conf.all.dad_transmits = 0...
This is the way ansible handles the reload sysctl task. It reads all lines and since there are ipv6 lines and ipv6 is disabled then it fails. 

Tested adding "ignoreerrors: yes" which did not fix the issue. 

#Auditd restart
When running "killproc auditd -TERM && systemctl start auditd", the auditd service does not consistently start. 
Running "killproc auditd -TERM" and "systemctl start auditd" as seperate commands the auditd service starts properly.

### Expected behavior

Suggestion for sysctl: 
set reload to no and run "/sbin/sysctl --load" outside of ansible. 
    reload: no
    ignoreerrors: yes

Suggestion for auditd:
Update the handler to run commands seperate. 
- name: kill auditd
  ansible.builtin.command: killproc auditd -TERM
  listen: restart auditd

- name: start auditd
  ansible.builtin.command: systemctl start auditd
  listen: restart auditd

or 
- name: restart auditd
  ansible.builtin.command: killproc auditd -TERM
  notify: start auditd

- name: start auditd
  ansible.builtin.command: systemctl start auditd

**Comment by rlakey** [comment]
I was looking at this command instead "pkill -SIGHUP auditd" previously.  It should cause auditd to reload it's config.

https://linux.die.net/man/8/auditd

**Comment by pstearns** [comment]
One thing to consider is when running "pkill -SIGHUP auditd" and if auditd is not currently running, it will not start automatically. You will still need to specifically call "systemctl start auditd".

**Comment by rlakey** [comment]
I'll have to test but I was thinking the task to enable and make sure auditd was started would catch that. May cause an error though depending on which order they are ran in.

**Comment by pstearns** [comment]
In testing, the most consistent way is to use the commands separately, with RESTART AUDIT calling START AUDIT. 
This will ensure that service is started and always specify the order. 

name: restart auditd
ansible.builtin.command: pkill -SIGHUP auditd
notify: start auditd

name: start auditd
ansible.builtin.command: systemctl start auditd

Using "pkill -SIGHUP auditd" vs "killproc auditd -TERM" doesn't seem to make a difference. Other than gracefully reloading auditd if I am understanding it correctly.
