### ISSUE TITLE
VCSA 6.7 ansible script error

### ISSUE THREAD

**Issue by jakobjohns** [vmware/dod-compliance-and-automation#105]
### Describe the bug

Within the main.yml for the eam, photon, and perfcharts - the line containing "ansible.builtin.include_tasks" is mispelled to "ansibie.builtin.include_tasks" and throws an error (obviously) when running it

### Reproduction steps

1. run main.yaml using command found in README

### Expected behavior

should run without error but does not due to the misspelling issue.

### Additional context

not sure if this is an issue anywhere else and would just run through some of the documents.

**Comment by rlakey** [comment]
Thanks for reporting that. I guess the linter doesn't check for correct FQCNs just that they are in that format.
