### ISSUE TITLE
[vSphere][7.0][VCUI-70-000007] InSpec test causes long delay when processing

### ISSUE THREAD

**Issue by pstearns** [vmware/dod-compliance-and-automation#106]
### Describe the bug

Noticed that on the latest vSphere 7 v1r4 that Inspec Profiles take a lot longer.
Tracked down to VCUI-70-000007. 

### Reproduction steps

New version of VCUI-70-000007 takes longer to process. 
Inspec 5.18.14
ruby 2.7.4p191
RHEL 8.6

### Expected behavior

The current check has to process files twice. Suggestion is to use the "root or users" instead. 
CURRENT:
  command("find '#{input('logPath')}' -type f -xdev").stdout.split.each do |fname|
    describe.one do
      describe file(fname) do
        it { should_not be_writable.by('others') }
        its('owner') { should cmp 'vsphere-ui' }
        its('group') { should cmp 'users' }
      end
      describe file(fname) do
        it { should_not be_writable.by('others') }
        its('owner') { should cmp 'vsphere-ui' }
        its('group') { should cmp 'root' }
      end
    end
  end

SUGGESTED:
 command("find '#{input('logPath')}' -type f -xdev").stdout.split.each do |fname|
    describe file(fname) do
      it { should_not be_writable.by('others') }
      its('owner') { should cmp 'vsphere-ui' }
      its('group') { should cmp('root').or cmp('users') }
    end
  end
end

**Comment by rlakey** [comment]
Good idea I'll add that to the next round. I haven't used that method much so can never remember the syntax!
