### ISSUE TITLE
INSPEC: ESXI-70-000008 and ESXI-70-000007 fail with an error

### ISSUE THREAD

**Issue by pbarrette** [vmware/dod-compliance-and-automation#121]
### Describe the bug

The ESXI-70-000007 and ESXI-70-000008 controls will always produce errors resulting in control failure.

### Reproduction steps

1. Execute inspec controls ESXI-70-000007 and ESXI-70-000008 against a compliant system.

### Expected behavior

Systems compliant with the controls should be marked as compliant.

### Additional context

In line 148 of "ESXI-70-000007.rb" the command contains:
Get-AdvancedSetting -Name Get-AdvancedSetting -Name Config.Etc.issue

The duplicate "Get-AdvancedSetting -Name" makes this an invalid PowerCLI command.

The same is true of line 59 of "ESXI-70-000008.rb"

**Comment by rlakey** [comment]
Thanks for the report this should be fixed now.
