### ISSUE TITLE
INSPEC: ESXI-70-000003 fails with multiple exception users (Windows)

### ISSUE THREAD

**Issue by pbarrette** [vmware/dod-compliance-and-automation#124]
### Describe the bug

The ESXI-70-000003 control will fail if multiple Lockdown Exception users are present.

There is no obvious way to specify multiple lockdown exception users in the inputs.yml file.

### Reproduction steps

1. Configure multiple Lockdown Exception users
2. Add those users to the exceptionUsers of your input.yml file
3. Execute an inspec scan against control ESXI-70-000003.

### Expected behavior

There should be a way to specify multiple users in the "exceptionUsers" field which results in a compliant scan.

### Additional context

Using Powershell version 5.1 on Windows 2019 and InSpec 5.21.29.

The stdout.strip also contains CRLF line endings for each user in the returned list, which fails against just about anything I can do with the input.yml file

I have only been able to correct this by adding my exceptionUsers in single quotes and modifying line 55 of the "ESXI-70-000003.rb" file to read:

```
command = "$vmhost = Get-VMHost -Name #{vmhost} | Get-View; $out = (Get-View $vmhost.ConfigManager.HostAccessManager).QueryLockdownExceptions() | Out-String; $out.Replace(\"`r`n\",\",\").TrimEnd(',')"
```

This is obviously not the ideal way to handle the issue, but I am not too familiar with Ruby or InSpec. The single quoted exceptionUsers field is needed to compensate for AD domain users with a backslash.

**Comment by pstearns** [comment]
It may be best to switch to array and then use "should be in" similar to the NTP suggestion. 
[https://github.com/vmware/dod-compliance-and-automation/issues/125#issuecomment-1410767489](url)

**Comment by rlakey** [comment]
@pbarrette try out the fix i pushed. I updated the input variable to be an array so you can just specify the users that should be in there like ['user1', 'user2].  I don't have AD users in my current test environment so please verify.

**Comment by pbarrette** [comment]
@rlakey
This works with the array values in double quotes.

Just as a warning, for AD users it fails on the backslash if you use single quotes.

**Comment by rlakey** [comment]
Ok i'll put a note in the inspec.yml about that. Thanks for checking.
