### ISSUE TITLE
INSPEC: ESXI-70-000046 fails with multiple NTP servers.

### ISSUE THREAD

**Issue by pbarrette** [vmware/dod-compliance-and-automation#125]
### Describe the bug

If multiple NTP servers are configured in ESXi and your input.yml file has correct values for ntpServer1 and ntpServer2, the control fails as non-compliant.

### Reproduction steps

1. Configure 2 NTP servers in ESXi
2. Add those NTP servers to the input.yml file as ntpServer1 and ntpServer2
3. Execute an inspec scan against ESXI-70-000046.

### Expected behavior

Multiple NTP servers should be handled correctly resulting in a compliant scan.

### Additional context

Using Windows 2019, Powershell 5.1 and InSpec 5.21.29

The stdout.strip is returning multiple lines from Get-VMHostNTPServer, complete with CRLF line endings.

The comparisons are being done as "should cmp" which fails.

I have modified lines 74 and 75 to be "should match" to correct the issue, but as I am not proficient with Ruby or InSpec, I cannot be certain that this is the best action.

**Comment by pstearns** [comment]
Another option would be to use an array on the input.yml. 
And then use "should be_in"

```
if !vmhosts.empty?
    vmhosts.each do |vmhost|
      command = "Get-VMHost -Name #{vmhost} | Get-VMHostService | Where {$_.Label -eq 'NTP Daemon'} | Select-Object -ExpandProperty Policy"
      describe powercli_command(command) do
        its('stdout.strip') { should cmp 'on' }
      end
      command = "Get-VMHost -Name #{vmhost} | Get-VMHostService | Where {$_.Label -eq 'NTP Daemon'} | Select-Object -ExpandProperty Running"
      describe powercli_command(command) do
        its('stdout.strip') { should cmp 'true' }
      end
      command = "Get-VMHost -Name #{vmhost} | Get-VMHostNTPServer"
      ntps = powercli_command(command).stdout.split
      ntps.each do |ntp|
        describe ntp do
          it { should be_in "#{input("ntpServers")}" }
        end
      end
    end
```

**Comment by pbarrette** [comment]
I agree that an array would probably be best here. It's clearly already in use for the vCenter check in the inputs-example.yml.

I haven't actually made it into vCenter yet though. This is the first time I'm using inspec and this repo and I'm having a difficult enough time getting through the bugs of the ESXi checks.

My suggested change was made with the concern of the wider userbase not knowing that they would need to change their input file format.

**Comment by rlakey** [comment]
Made quite a few updates to this test. It uses an array now as well and should work fine on both windows and linux.
