### ISSUE TITLE
[vSphere][7.0][VCLU-70-000007] Ownership and permission of log files not persisted.

### ISSUE THREAD

**Issue by pbarrette** [vmware/dod-compliance-and-automation#133]
### Describe the bug

This vulnerability is looking for proper permissions and ownership of files in the `/var/log/vmware/lookupsvc/` directory.

The SRG Fix Text states that permissions should be changed using:
`chmod 640 /var/log/vmware/lookupsvc/<file>`

And ownership should be changed using:
`chown root:root /var/log/vmware/lookupsvc/<file>`

A restart of the appliance results in the lookup service reverting permissions back to `644` as well as owner and group being reverted to `lookupsvc`

### Reproduction steps

1. Connect to the VCSA via SSH.
2. Execute `find /var/log/vmware/lookupsvc -xdev -type f -a '(' -perm /137 -o -not -user root -o -not -group root ')' -exec chmod 640 \;`
3. Execute `find /var/log/vmware/lookupsvc -xdev -type f -a '(' -perm /137 -o -not -user root -o -not -group root ')' -exec chown root:root \;`
4. Restart the VCSA.
5. Review the file permissions with `find /var/log/vmware/lookupsvc -xdev -type f -a '(' -perm /137 -o -not -user root -o -not -group root ')' -exec ls -ld {} \;`

### Expected behavior

Either:
1. The STIG should be changed to account for the default behavior of the lookup service logging, or
2. The default behavior of the lookup service logging should be changed to be more secure, or
3. The STIG Fix Text should include instructions for the setting of a umask and ACL.

### Additional context

After an appliance restart, the permissions look like this:
```
root@vcenter [ ~ ]# find /var/log/vmware/lookupsvc -xdev -type f -a '(' -perm /137 ')' -exec ls -ld {} \;
-rw-r--r-- 1 lookupsvc lookupsvc 1048872 Feb  6 11:45 /var/log/vmware/lookupsvc/vmware-lookupsvc-gc.log.0
-rw-r--r-- 1 lookupsvc lookupsvc 1899 Feb  6 00:00 /var/log/vmware/lookupsvc/tomcat/catalina.2023-02-06.log
-rw-r--r-- 1 lookupsvc lookupsvc 0 Feb  3 09:19 /var/log/vmware/lookupsvc/tomcat/host-manager.2023-02-03.log
-rw-r--r-- 1 lookupsvc lookupsvc 1899 Feb  4 00:00 /var/log/vmware/lookupsvc/tomcat/catalina.2023-02-04.log
-rw-r--r-- 1 lookupsvc lookupsvc 1899 Feb  5 00:00 /var/log/vmware/lookupsvc/tomcat/catalina.2023-02-05.log
-rw-r--r-- 1 lookupsvc lookupsvc 45240 Feb  3 10:37 /var/log/vmware/lookupsvc/tomcat/catalina.2023-02-03.log
-rw-r--r-- 1 lookupsvc lookupsvc 0 Feb  3 09:19 /var/log/vmware/lookupsvc/tomcat/manager.2023-02-03.log
-rw-r--r-- 1 lookupsvc lookupsvc 2358 Feb  3 09:19 /var/log/vmware/lookupsvc/tomcat/localhost.2023-02-03.log

**Comment by rlakey** [comment]
The check command will be updated in a future STIG release as follows:
```find /var/log/vmware/lookupsvc -xdev -type f -a '(' -perm /137 -o -not -user lookupsvc -o -not -group lookupsvc ')' -exec ls -ld {} \;```

**Comment by FRCWESTPAC** [comment]
The associated STIG hasn't yet been updated. Even with the aforementioned change as indicated by @rlakey , the command still yields output (see below) which results in a finding. The the user and group ownership is indicated as 'lookupsvc', so I'm not understanding why there is still output shown. Grateful for any feedback.

 -rw-r--r-- 1 lookupsvc lookupsvc 1048813 Apr 12 20:12 /var/log/vmware/lookupsvc/vmware-lookupsvc-gc.log.8
-rw-r--r-- 1 lookupsvc lookupsvc 1049150 May 22 16:15 /var/log/vmware/lookupsvc/vmware-lookupsvc-gc.log.3
-rw-r--r-- 1 lookupsvc lookupsvc 1049268 May 20 10:19 /var/log/vmware/lookupsvc/vmware-lookupsvc-gc.log.2
-rw-r--r-- 1 lookupsvc lookupsvc 650605 May 11 05:54 /var/log/vmware/lookupsvc/vmware-lookupsvc-gc.log.5.current
-rw-r--r-- 1 lookupsvc lookupsvc 6440548 May 22 00:00 /var/log/vmware/lookupsvc/tomcat/localhost_access.2023-05-21.log
-rw-r--r-- 1 lookupsvc lookupsvc 2990 May 23 22:25 /var/log/vmware/lookupsvc/tomcat/localhost.2023-05-23.log
-rw-r--r-- 1 lookupsvc lookupsvc 2347626 May 23 23:59 /var/log/vmware/lookupsvc/tomcat/localhost_access.2023-05-23.log
-rw-r--r-- 1 lookupsvc lookupsvc 6450932 May 18 23:59 /var/log/vmware/lookupsvc/tomcat/localhost_access.2023-05-18.log
-rw-r--r-- 1 lookupsvc lookupsvc 0 May 24 00:14 /var/log/vmware/lookupsvc/tomcat/host-manager.2023-05-24.log
-rw-r--r-- 1 lookupsvc lookupsvc 0 May 23 06:31 /var/log/vmware/lookupsvc/tomcat/host-manager.2023-05-23.log
-rw-r--r-- 1 lookupsvc lookupsvc 6487757 May 17 23:59 /var/log/vmware/lookupsvc/tomcat/localhost_access.2023-05-17.log
-rw-r--r-- 1 lookupsvc lookupsvc 12711 May 24 00:14 /var/log/vmware/lookupsvc/tomcat/catalina.2023-05-24.log
-rw-r--r-- 1 lookupsvc lookupsvc 6566245 May 22 23:59 /var/log/vmware/lookupsvc/tomcat/localhost_access.2023-05-22.log
-rw-r--r-- 1 lookupsvc lookupsvc 6377757 May 14 23:59 /var/log/vmware/lookupsvc/tomcat/localhost_access.2023-05-14.log
-rw-r--r-- 1 lookupsvc lookupsvc 0 May 24 00:14 /var/log/vmware/lookupsvc/tomcat/manager.2023-05-24.log
-rw-r--r-- 1 lookupsvc lookupsvc 6400511 May 20 23:59 /var/log/vmware/lookupsvc/tomcat/localhost_access.2023-05-20.log
-rw-r--r-- 1 lookupsvc lookupsvc 89141 May 23 22:25 /var/log/vmware/lookupsvc/tomcat/catalina.2023-05-23.log
-rw-r--r-- 1 lookupsvc lookupsvc 1453972 May 24 04:39 /var/log/vmware/lookupsvc/tomcat/localhost_access.log
-rw-r--r-- 1 lookupsvc lookupsvc 0 May 23 06:31 /var/log/vmware/lookupsvc/tomcat/manager.2023-05-23.log
-rw-r--r-- 1 lookupsvc lookupsvc 6369855 May 15 23:59 /var/log/vmware/lookupsvc/tomcat/localhost_access.2023-05-15.log
-rw-r--r-- 1 lookupsvc lookupsvc 6462185 May 16 23:59 /var/log/vmware/lookupsvc/tomcat/localhost_access.2023-05-16.log
-rw-r--r-- 1 lookupsvc lookupsvc 6517477 May 19 23:59 /var/log/vmware/lookupsvc/tomcat/localhost_access.2023-05-19.log
-rw-r--r-- 1 lookupsvc lookupsvc 731 May 24 00:14 /var/log/vmware/lookupsvc/tomcat/localhost.2023-05-24.log
-rw-r--r-- 1 lookupsvc lookupsvc 281142 Apr 27 23:14 /var/log/vmware/lookupsvc/vmware-lookupsvc-gc.log.6.current
-rw-r--r-- 1 lookupsvc lookupsvc 1048716 May 15 11:34 /var/log/vmware/lookupsvc/vmware-lookupsvc-gc.log.0
-rw-r--r-- 1 lookupsvc lookupsvc 1048971 Apr 14 20:58 /var/log/vmware/lookupsvc/vmware-lookupsvc-gc.log.9
-rw-r--r-- 1 lookupsvc lookupsvc 191629 May 24 04:38 /var/log/vmware/lookupsvc/vmware-lookupsvc-gc.log.0.current
-rw-r--r-- 1 lookupsvc lookupsvc 1049250 May 18 03:29 /var/log/vmware/lookupsvc/vmware-lookupsvc-gc.log.1
-rw-r--r-- 1 lookupsvc lookupsvc 1048824 Apr 10 19:50 /var/log/vmware/lookupsvc/vmware-lookupsvc-gc.log.7

**Comment by pstearns** [comment]
This is addressed in the known issues.

https://github.com/vmware/dod-compliance-and-automation/blob/18bb2e38b4b970863ba8bfbc9d504a7eff4b4aa9/vsphere/7.0/docs/known-issues.md

This has been discussed as a future correction to accept the permission lookupsvc:lookupsvc in future stig release. 

The current stig command looks for Root:root one can argue that lookupsvc is less permissive than root root and there the intent of the stig check is meet even though the current command shows open.
