### ISSUE TITLE
[vSphere][7.0][VCST-70-000028] STS catalina.properties not using updated smartcard port

### ISSUE THREAD

**Issue by scjohnson1988** [vmware/dod-compliance-and-automation#135]
### Describe the bug

Per VMware documentation (https://kb.vmware.com/s/article/90542), as of 7.0 U3i, the smartcard port was changed to 3128.  My smartcard logins were not working after running the playbook.  I can't recall if I ran the playbook before or after patching to 7.0 U3i, but after using the playbook, PKI logins stopped working.  After doing some testing and realizing port 3128 wasn't listening on the server, I examined a non-STIGed vCenter on the same version and noticed it includes "bio-ssl-clientauth.https.port=3128" config value on the catalina.properties file. Upon adding the value and restarting STS, the issue was fixed.

The catalina.properties template file likely needs to just include "bio-ssl-clientauth.https.port=3128".

### Reproduction steps

1. Run playbook
2. Attempt to use smartcard login
3. Error along the lines of "Username and password required" and no prompt requesting a cert is generated
...

### Expected behavior

Be prompted for smartcard login when requested.

**Comment by rlakey** [comment]
Thanks for the report @scjohnson1988 this is on my list of updates for the next round.
