### ISSUE TITLE
[vSphere][7.0][VCPG-70-000006] The check command output may display some tables not owned by "vc"

### ISSUE THREAD

**Issue by rlakey** [vmware/dod-compliance-and-automation#139]
### Describe the bug

When running the check command `/opt/vmware/vpostgres/current/bin/psql -d VCDB -x -U postgres -c "\dt;"|grep Owner|grep -v vc` the output may list some tables not owned by the vc user.

For example:

 Schema |                  Name                   |       Type        |  Owner   
--------+-----------------------------------------+-------------------+----------
 vc     | pg_capture_perf_metadata                | table             | postgres
 vc     | vpx_authz_global_permissions            | table             | postgres
 vc     | vpx_authz_privileges                    | table             | postgres
 vc     | vpx_authz_roles                         | table             | postgres
 vc     | vpx_authz_roles_privileges              | table             | postgres
 vc     | vpx_cluster_vcls_datastore              | table             | postgres
 vc     | vpx_host_memory_tier_info               | table             | postgres
 vc     | vpx_host_service_mode_state             | table             | postgres
 vc     | vpx_host_state_encryption_info          | table             | postgres
 vc     | vpx_vcdb_ndu_exp                        | table             | postgres
 vc     | vpx_vcdb_ndu_exp_app                    | table             | postgres
 vc     | vpx_vcdb_ndu_rvt                        | table             | postgres
 vc     | vpx_vcdb_proc_trk                       | table             | postgres
 vc     | vpx_vcls_drs_wf_counters                | table             | postgres

This is due to an upgrade and can be left as is or the owner can be updated to "vc".

### Reproduction steps

None

### Expected behavior

No output from the check command.

**Comment by scpfinoue** [comment]
IRT to this STIG item, when I run the check command I get this output.
Owner | postgres
Owner | postgres
Owner | postgres
Owner | postgres
Owner | postgres

Can you explain this output.  What is the table name that is owned by postgres?  If I were to run the fix what <tablename> do I use?

**Comment by rlakey** [comment]
@scpfinoue If you take the grep statements off the command you'll get the full output with the table names.

`/opt/vmware/vpostgres/current/bin/psql -d VCDB -x -U postgres -c "\dt;"`

Also see:  https://github.com/vmware/dod-compliance-and-automation/blob/master/vsphere/7.0/docs/known-issues.md#vcpg-70-000006-the-check-command-output-may-display-some-tables-not-owned-by-vc

**Comment by scpfinoue** [comment]
I found 71 tables owned by postgres using this command
> psql -d VCDB -x -U postgres
>select tablename,tableowner from pg_catalog.pg_tables where tableowner='postgres'

Question, changing ownership of all these 71 tables to 'vc' will NOT cause any issues?

**Comment by rlakey** [comment]
@scpfinoue That command is not filtering out some tables as \dt does. Can you email your results to stigs@vmware.com and I'll look at your output?
