### ISSUE TITLE
[vSphere][7.0][Start_VMS] Post Remediation calls for Start_VM, but does not start

### ISSUE THREAD

**Issue by ben219brown** [vmware/dod-compliance-and-automation#141]
### Describe the bug

Running the VM remediation via Ansible, the final step is a power on of the virtual machine. Command executes but VM does not start.

Reviewed \handlers\main.yml and came to the conclusion it was unable to retrieve a list of virtual machines being remediated. 

Added first 25 lines from vm_lockdown.yml to \handlers\main.yml to retrieve the list in the same fashion. Modified PowerCLI code lines 41-47 in \handlers\main.yml to include exclusion_list variable. Problem corrected although maybe a cleaner way to accomplish this?

New block to pull in vm list and exclusions

---
- name: Get All VM Hostnames Part 1 of 2
  ansible.builtin.shell:
    cmd: |
      Connect-VIServer -Server {{ vcenter_hostname }} -User '{{ vcenter_username }}' -Password '{{ vcenter_password }}';
      $exclusion_list = "{{ exclusion_list }}";
      $vms = Get-VM | where {$_.name -notMatch $exclusion_list} | Select-Object -ExpandProperty Name;
      $vms | Out-File /tmp/vm_machines.txt
  when:
    - get_vms | bool
  args:
    executable: /usr/bin/pwsh
  tags:
    - always

- name: Get All VM Hostnames Part 2 of 2
  ansible.builtin.shell:
    cmd: cat /tmp/vm_machines.txt
  register: vm_machines
  when:
    - vm_list is defined
  args:
    executable: /usr/bin/bash
  tags:
    - always

New block for start_vms

- name: start_vms
  ansible.builtin.shell:
    cmd: |
      Connect-VIServer -Server {{ vcenter_hostname }} -User '{{ vcenter_username }}' -Password '{{ vcenter_password }}';
      $exclusion_list = "{{ exclusion_list }}";
      $vms = Get-VM | where {$_.name -notMatch $exclusion_list} | Select-Object -ExpandProperty Name;
      ForEach($vm in $vms){
        $powered_state = Get-VM $vm | Select-Object PowerState;
        if($powered_state.PowerState -eq "PoweredOff"){
          Start-VM -VM $vm -Confirm:$False;
        }
      }

### Reproduction steps

1.Run the remediation
2.
3.
...

### Expected behavior

Virtual Machine should power on post remediation

**Comment by rlakey** [comment]
@HerbBoy Any thoughts?

**Comment by HerbBoy** [comment]
So my first question is do you have the following STIGs enabled:

- vmch_70_000008 
- vmch_70_000009

**Comment by ben219brown** [comment]
Yes, all were enabled.

**Comment by HerbBoy** [comment]
@ben219brown  Please pull down my fork and let me know if moving it to main fixes this issue for you. i was unable to replicate your issue with the handlers so i am hoping moving it to main fixes this. If it does i will submit a PR.

**Comment by HerbBoy** [comment]
> @HerbBoy VM still does not power on post remediation. Are you by chance testing while having an active powershell connection to your vcenter or host?

I do usually (hard to say if it was everytime) - but I am usually on my RHEL8 test node just testing against a few test vms i create. If you think thats the issue I will re-investigate.

I have ran this in ops a few times and i dont think i was actively connected and talking to the vcenter via powercli but in hopes to re-create this and debug with you i would like to replicate.

**Comment by HerbBoy** [comment]
> 
a question: what is your environment looking like: what are you running ansible from (RHEL or a different OS).

**Comment by ben219brown** [comment]
I am running it from RHEL7 right now. I have also been testing via Ubuntu using Windows wsl.exeGet Outlook for Android

**Comment by rlakey** [comment]
Closing since the contributor of these two particular playbooks hasn't been maintaining them. I put a note in the readme of both that VMware does not maintain them.
