### ISSUE TITLE
[VSPHERE][70][ESXI][ESXI-70-000047]Fails to Set VIB Acceptance Level

### ISSUE THREAD

**Issue by ben219brown** [vmware/dod-compliance-and-automation#144]
### Describe the bug

When running the remediation,  system errors on title check. 

 "msg": "value of acceptance_level must be one of: community, partner, vmware_accepted, vmware_certified, got: PartnerSupported"}

edited \vars\main.yml line 125 to:

vib_accept_level: partner

edited \tasks\esxi.yml

- name: ESXI-70-000047 - The ESXi Image Profile and vSphere Installation Bundle (VIB) Acceptance Levels must be verified.
  community.vmware.vmware_host_acceptance:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    esxi_hostname: "{{ item.value.hostname }}"
    validate_certs: "{{ validate_certs }}"
    acceptance_level: "{{ vib_accept_level }}"
    state: present
  with_dict:
    - "{{ esxi_hosts }}"
  when:
    - esxi_70_000047 | bool
  tags:
    - ESXI-70-000047

This added state: present, without parameter, check will run and output current setting, but not modify to the chosen setting. 

Reran, check completed without issue

### Reproduction steps

1.Run ESXI-70-000047
2.
3.
...

### Expected behavior

VIB Acceptance level changes to Partner Supported

**Comment by rlakey** [comment]
Closing since the contributor of these two particular playbooks hasn't been maintaining them. I put a note in the readme of both that VMware does not maintain them.
