### ISSUE TITLE
[VSPHERE][70][VMCH-70-000026][VMCH-70-000027]Incorrect Key

### ISSUE THREAD

**Issue by ben219brown** [vmware/dod-compliance-and-automation#145]
### Describe the bug

Ansible configuration vm_lockdown.yml

Lines 518 and  535

518      - key: vmx.log.rotateSize

535       - key: vmx.log.keepOld

This is incorrect per STIG guidance.

STIG calls for log.rotateSize and log.keepOld

### Reproduction steps

1.
2.Run the remediation
3.
...

### Expected behavior

value is changed to log. and not vmx.log.

**Comment by rlakey** [comment]
Closing since the contributor of these two particular playbooks hasn't been maintaining them. I put a note in the readme of both that VMware does not maintain them.
