### ISSUE TITLE
STIG ID: PHTN-30-00003/The Photon operating system must require authentication upon booting into single-user and maintenance modes.

### ISSUE THREAD

**Issue by scpfinoue** [vmware/dod-compliance-and-automation#149]
### Describe the bug

Will implementing this CAT-1 STIG block the ability to reset root password: https://kb.vmware.com/s/article/2147144.  I'm not sure what remediating this STIG item will do to VCSA.

The VSphere 7 STIG says PHTN-30-00003:
Rule Title: The Photon operating system must require authentication upon booting into single-user and maintenance modes.

Discussion: If the system does not require authentication before it boots into single-user mode, anyone with console access to the system can trivially access all files on the system. GRUB2 is the boot loader for Photon OS and can be configured to require a password to boot into single-user mode or make modifications to the boot menu.

Note: Photon does not support building grub changes via grub2-mkconfig.

Check Text: At the command line, run the following command:

# grep -i ^password_pbkdf2 /boot/grub2/grub.cfg

If there is not output, this is a finding.

If the output does not begin with "password_pbkdf2 root", this is a finding.

### Reproduction steps

1.None 
2.
3.
...

### Expected behavior

Need clarification if this STIG will block me from resetting root password if needed.

**Comment by rlakey** [comment]
@scpfinoue No, this grub password is independent of the normal password for root.
