### ISSUE TITLE
enablemob comparison

### ISSUE THREAD

**Issue by petedawood** [vmware/dod-compliance-and-automation#15]
stigsettings.enablemob value is boolean
then it's defined as a [string] under esxi-65-000034
$settingvalue = [string]$stigsettings.enablemob.values

$currentvalue.value when populated is a bool value.
so when the compare occurs 

if ($currentvalue.value -ne $settingvalue) {.....

it will always be true because a bool compared to a string will always be different.

recommend
if (
       ([string]$currentvalue.value) -ne $settingvalue 
){ .....

**Comment by rlakey** [comment]
petedawood can you submit a pull request with the suggested change?

**Comment by rlakey** [comment]
Closing since this was for 6.5 and it is no longer supported.
