### ISSUE TITLE
[vSphere][7.0][ESXI-70-000097] The ESXi CIM service must be disabled

### ISSUE THREAD

**Issue by daveho5392** [vmware/dod-compliance-and-automation#151]
### Describe the bug

If the CIM Server policy is not set correctly, but the service isn't running, the script will not fix the incorrect policy

### Reproduction steps

1.Set the CIM Server policy to something other than "start and stop manually"
2.Stop the CIM server services
3.Run the script
...

### Expected behavior

Recommend changing the IF statement from:

If($stigsettings.cimEnabled -eq $false)

To

If($vmhostservice.Running -eq $true -or $vmhostservice.Policy -ne "off")

**Comment by rlakey** [comment]
Fixed by https://github.com/vmware/dod-compliance-and-automation/commit/af22fc6142118d88abd0a07bb34dccb10bc03cf9
