### ISSUE TITLE
[vSphere][7.0][VMs] InSpec failing checks on VM names with spaces

### ISSUE THREAD

**Issue by pstearns** [vmware/dod-compliance-and-automation#160]
### Describe the bug

VMs with spaces in the name report no VMs found, skipping.  They also have () but I think its just the space. We are also working on updating our naming convention policy. 
Wondering if anyone has any ideas on getting the VM name to pass properly.

The issue is with the way the following strips and passes the VM name.    
`vm = powercli_command("Get-VM -Name #{vmName} | Sort-Object Name | Select -ExpandProperty Name").stdout.gsub("\r\n", "\n").split("\n")`

### Reproduction steps

Not working:   
```
unless vmName.empty?
    vms = powercli_command("Get-VM -Name #{vmName} | Sort-Object Name | Select -ExpandProperty Name").stdout.gsub("\r\n", "\n").split("\n")
  end
  unless allvms == false
    vms = powercli_command('Get-VM | Sort-Object Name | Select -ExpandProperty Name').stdout.gsub("\r\n", "\n").split("\n")
  end

  if !vms.empty?
    vms.each do |vm|
      command = "Get-VM -Name '#{vm}' | Get-AdvancedSetting -Name isolation.tools.dnd.disable | Select-Object -ExpandProperty Value"
      describe powercli_command(command) do
        its('stdout.strip') { should cmp 'true' }
      end
    end
  else
    describe 'No VMs found!' do
      skip 'No VMs found...skipping tests'
    end
  end
end
```

Working:
```
  vmName = input('vmName')
  command = "Get-VM -Name '#{vmName}' | Get-AdvancedSetting -Name isolation.tools.copy.disable | Select-Object -ExpandProperty Value"
  describe powercli_command(command) do
      its('stdout.strip') { should cmp 'true' }
  end
```

### Expected behavior

Check to find VMs with spaces in names.

### Additional context

Attempted adding quotes in various ways but couldn't get it to work.

**Comment by rlakey** [comment]
Are you just passing a single VM to the profile? That should be the only part where this would be a problem.


This part
```
  unless vmName.empty?
    vms = powercli_command("Get-VM -Name #{vmName} | Sort-Object Name | Select -ExpandProperty Name").stdout.gsub("\r\n", "\n").split("\n")
  end
```

If just scanning all VMs it should work with spaces in the names as we already have quotes around where we loop through VMs.

```
  vmName = input('vmName')
  allvms = input('allvms')
  vms = []

  unless vmName.empty?
    vms = powercli_command("Get-VM -Name #{vmName} | Sort-Object Name | Select -ExpandProperty Name").stdout.gsub("\r\n", "\n").split("\n")
  end
  unless allvms == false
    vms = powercli_command('Get-VM | Sort-Object Name | Select -ExpandProperty Name').stdout.gsub("\r\n", "\n").split("\n")
  end

  if !vms.empty?
    vms.each do |vm|
      command = "Get-VM -Name '#{vm}' | Get-AdvancedSetting -Name isolation.tools.dnd.disable | Select-Object -ExpandProperty Value"
      describe powercli_command(command) do
        its('stdout.strip') { should cmp 'true' }
      end
    end
  else
    describe 'No VMs found!' do
      skip 'No VMs found...skipping tests'
    end
  end
```

**Comment by pstearns** [comment]
Yes, I am just passing one VM since we are required to have a checklist for each VM. 

I did attempt using single quotes in the command like:
`  unless vmName.empty?
    vms = powercli_command("Get-VM -Name '#{vmName}'| Sort-Object Name | Select -ExpandProperty Name").stdout.gsub("\r\n", "\n").split("\n")
  end`
But that didn't work.

**Comment by pstearns** [comment]
This fixed it. I needed to add the "" when passing the VM name, along with the single quotes in the control.
Note I am using a wrapper script not input file. But it is working the same. 
```
$vm = get-vm
foreach ($vm in $vms){
     inspec exec $inspecPath -t vmware:// --input vmName="$vm" --show-progress --reporter json:$reportFile | Out-Null
}
```

Thanks
