### ISSUE TITLE
[vSphere][7.0][PHOTON] Ansible handling /etc/applmgmt/appliance

### ISSUE THREAD

**Issue by pstearns** [vmware/dod-compliance-and-automation#164]
### Describe the bug

For the following Photon checks:
PHTN-30-000002, PHTN-30-000021 - PHTN-30-000024, PHTN-30-000029, PHTN-30-000030, PHTN-30-000050, PHTN-30-000071, PHTN-30-000073, PHTN-30-000110, PHTN-30-000117

These have the following note:
On vCenter appliances, the equivalent file must be edited under "/etc/applmgmt/appliance"

Ansible updates the /etc/pam.d files but not the /etc/applmgmt/appliance

### Reproduction steps

1) Run ansible for any of the checks.
2) Verify /etc/pam.d files updated
3) Reboot and settings dont persist

Verified the settings arent added to /etc/applmgmt/appliance

### Expected behavior

Correct both /etc/pam.d files and/etc/applmgmt/appliance files.

I modified mine by adding a template to each of the checks that copies into the /etc/applmgmt/appliance.
Not sure if this is the best way.

**Comment by rlakey** [comment]
This is specific to vCenter and not Photon in general and is covered here: https://github.com/vmware/dod-compliance-and-automation/blob/master/vsphere/7.0/vcsa/ansible/vmware-vcsa-7.0-stig-ansible-hardening/roles/misc/tasks/misc.yml

**Comment by pstearns** [comment]
Thank you for the response. I will dig into it next week.

**Comment by pstearns** [comment]
This is working when using the misc task. I was using ansible with tags and therefore skipping the misc task. 
I just added in the tags on the misc so they are called if only doing the pam stuff.
