### ISSUE TITLE
[vSphere][7.0][VCPG-70-000020] UTC vs Etc/UTC

### ISSUE THREAD

**Issue by pstearns** [vmware/dod-compliance-and-automation#165]
### Describe the bug

This is not really a bug but this was a finding during recent inspection. 
VCPG-70-000020 - Postgres log time zone is not set to the STIG Expected result of Etc/UTC.

### Reproduction steps

1. /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "SHOW log_timezone;"
2. RESULT: UTC

### Expected behavior

 /opt/vmware/vpostgres/current/bin/psql -U postgres -A -t -c "SHOW log_timezone;"
RESULT: Etc/UTC

### Additional context

We didnt agree that this would be an open but got dinged on it anyway.
We did test setting the timezone to Etc/UTC without any observed problems. 
The Inspec check does not catch this as a finding nor does ansible correct it.

Possible solution paths: 
Update STIG wording
or Correct the inspec check and ansible fix to account

Thoughts?

**Comment by rlakey** [comment]
PostgreSQL has multiple ways to specify a timezone. The abbreviation and name and are functionally equivalent. The InSpec test accepts either but we can make the text more clear that either is ok.

You can see these with the following commands: 

SELECT * FROM pg_timezone_abbrevs;
SELECT * FROM pg_timezone_names;

UTC is actually the abbreviation for 8 names.

```
     name      | abbrev | utc_offset | is_dst
---------------+--------+------------+--------
 Universal     | UTC    | 00:00:00   | f
 UCT           | UTC    | 00:00:00   | f
 Zulu          | UTC    | 00:00:00   | f
 UTC           | UTC    | 00:00:00   | f
 Etc/Universal | UTC    | 00:00:00   | f
 Etc/UCT       | UTC    | 00:00:00   | f
 Etc/Zulu      | UTC    | 00:00:00   | f
 Etc/UTC       | UTC    | 00:00:00   | f
```

**Comment by pstearns** [comment]
Thank you. The command will help while explaining they are the same.

**Comment by pstearns** [comment]
Could this also be added to the known issue for clarity?

This addressed my question and be closed if needed. Thank you.

**Comment by rlakey** [comment]
Updated the known issues.
