### ISSUE TITLE
[vSphere][7.0][VCST-70-000021] Ansible <async-supported>true</async-supported> 

### ISSUE THREAD

**Issue by pstearns** [vmware/dod-compliance-and-automation#166]
### Describe the bug

Another minor item we got hit on during inspection.

Ansible places the <async-supported>true</async-supported> at top of filter as follows.
```
  <filter>
      <filter-name>setCharacterEncodingFilter</filter-name>
      <filter-class>
         org.apache.catalina.filters.SetCharacterEncodingFilter
      </filter-class>
      <async-supported>true</async-supported>
      <init-param>
         <param-name>encoding</param-name>
         <param-value>UTF-8</param-value>
      </init-param>
      <init-param>
         <param-name>ignore</param-name>
         <param-value>true</param-value>
      </init-param>
   </filter>
```
At the command prompt, run the following command:

`xmllint --format /usr/lib/vmware-sso/vmware-sts/conf/web.xml | sed '2 s/xmlns=".*"//g' | xmllint --xpath '/web-app/filter/filter-name[text()="setCharacterEncodingFilter"]/parent::filter' -`

Expected result:
```
   <filter>
      <filter-name>setCharacterEncodingFilter</filter-name>
      <filter-class>
         org.apache.catalina.filters.SetCharacterEncodingFilter
      </filter-class>
      <init-param>
         <param-name>encoding</param-name>
         <param-value>UTF-8</param-value>
      </init-param>
      <init-param>
         <param-name>ignore</param-name>
         <param-value>true</param-value>
      </init-param>
      <async-supported>true</async-supported>
   </filter>
```

### Reproduction steps

After running Ansible:

At the command prompt, run the following command:

`xmllint --format /usr/lib/vmware-sso/vmware-sts/conf/web.xml | sed '2 s/xmlns=".*"//g' | xmllint --xpath '/web-app/filter/filter-name[text()="setCharacterEncodingFilter"]/parent::filter' -`

RESULT:
```
  <filter>
      <filter-name>setCharacterEncodingFilter</filter-name>
      <filter-class>
         org.apache.catalina.filters.SetCharacterEncodingFilter
      </filter-class>
      <async-supported>true</async-supported>
      <init-param>
         <param-name>encoding</param-name>
         <param-value>UTF-8</param-value>
      </init-param>
      <init-param>
         <param-name>ignore</param-name>
         <param-value>true</param-value>
      </init-param>
   </filter>
```

### Expected behavior

At the command prompt, run the following command:
`xmllint --format /usr/lib/vmware-sso/vmware-sts/conf/web.xml | sed '2 s/xmlns=".*"//g' | xmllint --xpath '/web-app/filter/filter-name[text()="setCharacterEncodingFilter"]/parent::filter' -`

Expected result:

```
   <filter>
      <filter-name>setCharacterEncodingFilter</filter-name>
      <filter-class>
         org.apache.catalina.filters.SetCharacterEncodingFilter
      </filter-class>
      <init-param>
         <param-name>encoding</param-name>
         <param-value>UTF-8</param-value>
      </init-param>
      <init-param>
         <param-name>ignore</param-name>
         <param-value>true</param-value>
      </init-param>
      <async-supported>true</async-supported>
   </filter>

```

### Additional context

Since STIG is written: 
`If the output is does not match the expected result, **this is a finding**.`
This was counted as an open.

This is more a discussion topic than fix.

**Comment by rlakey** [comment]
Ok yea technically it will work in either location. We did implement some XML schema validation in 8 where it must be before the init-params so I was taking that into consideration in the ansible though in 7 it'll work as long as it is indented at the right level.

If the auditor needs a statement to clarify this just reach out and we can help.

**Comment by pstearns** [comment]
If you could add a statement to the known issues file, that would be great. Then we at least have somewhere to point the auditor to. 
This addressed my question and be closed if needed. Thank you.

**Comment by rlakey** [comment]
Updated the known issues.
