### ISSUE TITLE
[vSphere][7.0][	PHTN-30-000064] Cipher order

### ISSUE THREAD

**Issue by pstearns** [vmware/dod-compliance-and-automation#167]
### Describe the bug

Inspec passes ciphers check. Auditor review says it is open do to order of ciphers.

### Reproduction steps

Running Inspec shows: 
```
All Automated tests passed for the control 

 PASS -- Command: `sshd -T|&grep -i Ciphers` stdout.strip is expected to cmp == "ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com"
```

### Expected behavior

Expected result:
ciphers aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

### Additional context

Discussion: Does the order matter in this case?
Should this be an open if out of order?

Thanks again.

**Comment by rlakey** [comment]
No it shouldn't be a finding if in a different order. Order only matters to which cipher is offered first but any in the list are acceptable to use.

**Comment by rlakey** [comment]
In the Photon 4 guidance we have it written like this:

```
At the command line, run the following command to verify the running configuration of sshd:

# sshd -T|&grep -i Ciphers

Expected result:

ciphers aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

If the output matches the ciphers in the expected result or a subset thereof, this is not a finding.

If the ciphers in the output contain any ciphers not listed in the expected result, this is a finding.
```
