### ISSUE TITLE
Recommend change to error trapping

### ISSUE THREAD

**Issue by xcalabers** [vmware/dod-compliance-and-automation#2]
With a large number of hosts the VMware_vSphere_6.7_STIG_Compliance_Report.ps1 script currently takes hours to run. With the current error trapping if the script encounters any errors it exits. I would recommend instead changing this to track that check as non-compliant/error and continuing with the other checks. This way you get data about all successful checks and know which checks failed for review instead of getting nothing but a single error returned.

**Comment by rlakey** [comment]
How many hosts/vms were you running it against and where did it fail specifically?

**Comment by xcalabers** [comment]
I ran it against ~140 hosts with ~600 VMs. The VM portion ran successfully. On the ESXi checks the script encountered an error the check $VULID = "V-94005" due to an issue with the ESXi host. The error was due to a bad host and not a scripting error. I'd just prefer to catch the error, report on it, and continue with the remaining checks instead of "Exit -1".

**Comment by xcalabers** [comment]
Below is an example (IPs changed) crash after 2 hours of running successfully.

> 10:43:50 AM ...Checking ESXi Host 11.11.11.11 for The ESXi host must configure the firewall to restrict access to services running on the host.
C:\my\Path\VMware_vSphere_6.7_STIG_Compliance_Report.ps1 : Failed to check control with Vulnerability ID:V-94059 STIG ID:ESXI-65-000056 Severity:CAT II with Title: The ESXi host must 
configure the firewall to restrict access to services running on the host. on A_VM_vmName
At line:1 char:1
+ .\VMware_vSphere_6.7_STIG_Compliance_Report.ps1 -vccred $cred
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,VMware_vSphere_6.7_STIG_Compliance_Report.ps1
 
C:\my\Path\STIG_6.7\VMware_vSphere_6.7_STIG_Compliance_Report.ps1 : System.Management.Automation.MethodInvocationException: Exception calling "Join" with "2" argument(s): "Value cannot be 
null.
Parameter name: values" ---> System.ArgumentNullException: Value cannot be null.
Parameter name: values
   at System.String.Join(String separator, Object[] values)
   at CallSite.Target(Closure , CallSite , Type , String , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
At line:1 char:1
+ .\VMware_vSphere_6.7_STIG_Compliance_Report.ps1 -vccred $cred
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,VMware_vSphere_6.7_STIG_Compliance_Report.ps1
 
10:43:51 AM ...Disconnecting from vCenter Server 111.111.111.111

>

**Comment by xcalabers** [comment]
I'm not looking for a solution to this specific error but instead recommending a revision to overall error trapping with an option to just report on the error and continue. Maybe something like this:
`$ErrorDefaultAction = "Continue" #global variable can be 'Exit' or 'Continue'

function Handle-Error {
    [CmdletBinding()]
    Param(
        [Parameter(Mandatory=$True)]
        $Exception,
        [Parameter(Mandatory=$True)]
        [ValidateSet('Exit','Continue')]
        [string]$Action,
        [Parameter(Mandatory=$True)]
        [int]$ErrorCode,
        [Parameter(Mandatory=$True)]
        [ValidateSet('VM','ESXi','vCenter')]
        [string]$objType
    )
    
    Write-Error "Failed to check control with Vulnerability ID:$VULID STIG ID:$STIGID with Title: $Title on $($vm.name)"
    Write-Error $_.Exception
    
    $ErrorArray += New-Object PSObject -Property ([ordered]@{
                    "Name" = "" 
                    "Setting" = $VULID
                    "Value" = $Exception
                    "Expected" = "Error"
                    "Severity" = "Error"
                    "Compliant" = $false
    })
    
    switch($objType)
    {
        VM{
            
            $ErrorArray.Name = $vm.name 
            $vmsarray04 = Set-TableRowColor -ArrayOfObjects $ErrorArray -Red '$this.Compliant -eq $false' | Sort-Object -Property @{Expression = {$_.RowColor}; Ascending = $false},Name
            $vmsarrayall += $vmsarray    

        }

        ESXi{
            $ErrorArray.Name =  $vmhost.name
            $esxiarray12 = Set-TableRowColor -ArrayOfObjects $ErrorArray -Red '$this.Compliant -eq $false' | Sort-Object -Property @{Expression = {$_.RowColor}; Ascending = $false},Name
            $vmhostsarrayall += $esxiarray
        }
        vCenter{
            $ErrorArray.Name = $vcenter
            $vcarray36 = Set-TableRowColor -ArrayOfObjects $ErrorArray -Red '$this.Compliant -eq $false' | Sort-Object -Property @{Expression = {$_.RowColor}; Ascending = $false},Name
            $vcarrayall += $vcarray
        }

    }
    
    if ($Action -eq 'Exit') {
        Disconnect-VIServer -Server $vcenter -Force -Confirm:$false
        Exit $ExitCode
    }
}


try{
    somethingbroke
    }
Catch{
    Handle-Error  $_.Exception $ErrorDefaultAction 123 VM
}
`

**Comment by rthornburg** [comment]
So know this post is old but I am having this same issue where the report is exiting mid run and not giving any data on a single check failure, and I would like to implement your idea of the handle-error function. 

I have a couple questions about some of the code. 
1. In the objType sort, why did you add numbers to the arrays? ie  the 4,12, and 36 on vmsarray04,esxiarray12,vcarray36? the array's in the source dont have them. 
2. In the Catch what is the 123 VM for after the $ErrorDefaultAction call?

The current catch looks like this: 

Catch{
    Write-Error "Failed to check control with Vulnerability ID:$VULID STIG ID:$STIGID with Title: $Title on $($vm.name)"

    Write-Error $_.Exception

    Write-ToConsole "...Disconnecting from vCenter Server $vcenter"

    Disconnect-VIServer -Server $vcenter -Force -Confirm:$false

    Exit -1
}


To make your function work would I just need to change to something like this:

Catch{

    Write-Error "Failed to check control with Vulnerability ID:$VULID STIG ID:$STIGID with Title: $Title on $($vm.name)"

    Write-Error $_.Exception

    Handle-Error  $_.Exception $ErrorDefaultAction ?? is anything else needed??

}

**Comment by rlakey** [comment]
Closing since 6.7 is no longer supported. I believe these concerns are addressed in the newer versions as well.
