### ISSUE TITLE
VCEM-67-000005 in Ansible EAM Playbook not properly handling double quotations

### ISSUE THREAD

**Issue by scjohnson1988** [vmware/dod-compliance-and-automation#22]
Expected output from STIG is: pattern="%h %{X-Forwarded-For}i %l %u %t [%I] "%r" %s %b [Processing time %D msec] "%{User-Agent}i""

The output generated after running the eam playbook looks like: {User-Agent}i&quot;"

**Comment by rlakey** [comment]
Thanks for reporting this I'll check it out.

**Comment by scjohnson1988** [comment]
@rlakey I am (very slowly) implementing this new STIG.  As I'm sure you noticed when writing the playbooks, some of these requirements are very similar across most of the STIGs.  I just went through the PerfChats STIG and the nearly identical VCPF-67-000005 Playbook requirement has the same issue referenced above.  I'd imagine all STIGs dealing with "<STIG Name> must record user access in a format that enables monitoring of remote access." is going to have the same issue as identified here.

**Comment by scjohnson1988** [comment]
@rlakey I am running the commands via copy/paste from STIG Viewer into the terminal.  I am currently pasting `xmllint --xpath '/Server/Service/Engine/Host/Valve[@className="org.apache.catalina.valves.AccessLogValve"]'/@pattern /usr/lib/vmware-eam/web/conf/server.xml`, but the output displayed on the terminal would have `&quot;`.  This on Windows 2.14 STIG Viewer.

I have had issues in the past where some STIGs have frustratingly used `”` instead of `"`, but that doesn't appear to be the case here.

**Comment by rlakey** [comment]
I haven't been able to replicate this with the playbook on 6.7U3m and ansible 2.9.6.

This is after running the playbook.

` [ ~ ]# xmllint --xpath '/Server/Service/Engine/Host/Valve[@className="org.apache.catalina.valves.AccessLogValve"]'/@pattern /usr/lib/vmware-eam/web/conf/server.xml
 pattern="%h %{X-Forwarded-For}i %l %u %t [%I] &quot;%r&quot; %s %b [Processing time %D msec] &quot;%{User-Agent}i&quot;"`

**Comment by scjohnson1988** [comment]
I'll try to gather some more information tomorrow and perhaps try to manually enter the command to ensure it's not a cut/paste problem.  I'll also check which version of Ansible I'm using.

**Comment by scjohnson1988** [comment]
I ran some more tests on this today, but I'm still getting the same output.  Although, I am nearly certain it isn't malformed input.  When I open the `/usr/lib/vmware-sso/vmware-sts/conf/server.xml` file, I can visibly see the various `&quot;` entries in the config file.  The output is `pattern="%h %{X-Forwarded-For}i %l %u %t &quot;%r&quot; %s %b &quot;%{User-Agent}i&quot;"` from the command.  I did other checks of the playbook itself to ensure there were no weird carriage returns or anything, but I'm not seeing anything odd.

I am running the Playbook from a RHEL 7.9 VM using Ansible 2.9.19-1 using root on the vCenter.  I'll bring 2.9.21-1 next week which is the current release for RHEL.  I have both VMs setup pretty similarly and they're both displaying the same content.  Are you testing with Ubuntu or another distro?

**Comment by scjohnson1988** [comment]
Updated to Ansible 2.9.21-1 without any changes in output.

**Comment by rlakey** [comment]
I'm using Ubuntu 20.04. To I guess restate what you are currently seeing is the Ansible playbook is running ok but the xmllint check command isn't reporting correctly?

**Comment by scjohnson1988** [comment]
@rlakey Correct, the Playbook is running, but the lint check is showing the `&quot;`.  It's not an issue with the xmllint though - I checked the file with `vi` and it the actual file does have `&quot;` instead of `"`.

**Comment by rlakey** [comment]
It should be showing `&quot;` and not ".

**Comment by scjohnson1988** [comment]
Oh, I totally misunderstood you.  Interesting that STIG Viewer isn't handling this correctly, since in my experience during any audits, that's what they'll use for the reviews.  I can try to put in a request with the STIG helpdesk if that hasn't been done yet.

**Comment by balleman-tt** [comment]
The STIG Viewer group has received a report of this problem. It is expected to be resolved in the next release.

**Comment by rlakey** [comment]
Thank you that's good to hear they are fixing it.
