### ISSUE TITLE
VCPF-67-000022 in PerfChats Playbook Not Resolving STIG

### ISSUE THREAD

**Issue by scjohnson1988** [vmware/dod-compliance-and-automation#26]
After running the PerfCharts Playbook, the output for VCPF-67-000022 / STIG V-239423 is returning "XPath is empty" when running the command listed in the STIG Check:  xmllint --format /usr/lib/vmware-perfcharts/tc-instance/conf/web.xml | sed '2 s/xmlns=".*"//g' | xmllint --xpath '//param-name[text()="listings"]/parent::init-param' -

**Comment by rlakey** [comment]
Ok the playbook is removing this setting if it exists because the default is false if it is not present. We'll make a note to update the playbook or update the control with DISA.

The Inspec profile is checking for it not existing or it being false.

**Comment by scjohnson1988** [comment]
@rlakey I noticed this was also an issue on UI Tomcat STIG for VCUI-67-000021 for the same setting.  I haven't downloaded any updated playbooks in a few weeks though, so it may already be addressed.  I can create another issue if that'll make things easier.

**Comment by rlakey** [comment]
Nah you don't need to create another one.

**Comment by rlakey** [comment]
Should be fixed now in latest versions of playbook for 6.7 and 7.0.
