### ISSUE TITLE
Issue with vmware train install

### ISSUE THREAD

**Issue by netgurus** [vmware/dod-compliance-and-automation#268]
### Describe the bug

Unable to install train-vmware on new install. Bug or knowledge issue?

cinc-auditor 6.6.0 (also tried 6.8.1) fresh install on Windows 10.  

### Reproduction steps

Run this command,
cinc-auditor plugin install C:\Inspec\Profiles\8.0\v2r1-stig\vsphere\inspec\vmware-vsphere-8.0-stig-baseline\train-vmware-0.2.0.gem --debug

Receive this error.
[2024-11-07T15:13:43-06:00] ERROR: Unable to resolve dependency: user requested 'train-vmware (> 0)'
[2024-11-07T15:13:43-06:00] ERROR: Inspec::Plugin::V2::LoadError
[2024-11-07T15:13:43-06:00] ERROR: C:/cinc/cinc-auditor/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-6.6.0/lib/inspec/plugin/v2/loader.rb:208:in `rescue in activate_managed_gems_for_plugin'
C:/cinc/cinc-auditor/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-6.6.0/lib/inspec/plugin/v2/loader.rb:203:in `activate_managed_gems_for_plugin'
C:/cinc/cinc-auditor/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-6.6.0/lib/inspec/plugin/v2/loader.rb:313:in `fixup_train_plugin_status'
C:/cinc/cinc-auditor/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-6.6.0/lib/inspec/plugin/v2/loader.rb:40:in `block in initialize'
C:/cinc/cinc-auditor/embedded/lib/ruby/3.1.0/forwardable.rb:238:in `each'
C:/cinc/cinc-auditor/embedded/lib/ruby/3.1.0/forwardable.rb:238:in `each'
C:/cinc/cinc-auditor/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-6.6.0/lib/inspec/plugin/v2/loader.rb:39:in `initialize'
C:/cinc/cinc-auditor/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-6.6.0/lib/inspec/cli.rb:628:in `new'
C:/cinc/cinc-auditor/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-6.6.0/lib/inspec/cli.rb:628:in `<top (required)>'
<internal:C:/cinc/cinc-auditor/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:C:/cinc/cinc-auditor/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
C:/cinc/cinc-auditor/embedded/lib/ruby/gems/3.1.0/gems/cinc-auditor-bin-6.6.0/bin/cinc-auditor:11:in `<top (required)>'
C:/cinc/cinc-auditor/bin/cinc-auditor:281:in `load'
C:/cinc/cinc-auditor/bin/cinc-auditor:281:in `<main>'

Run this command
PS C:\Windows\System32> cinc-auditor plugin list

Receive this error
[2024-11-07T15:21:21-06:00] ERROR: Unable to resolve dependency: user requested 'train-vmware (> 0)'
[2024-11-07T15:21:21-06:00] ERROR: Run again with --debug for a stacktrace.
PS C:\Windows\System32>

### Expected behavior

Ruby gem should install

**Comment by rlakey** [comment]
@netgurus I haven't been able to duplicate this on Windows 11 in either Powershell or Powershell Core with cinc-auditor 6.8.1.

Since your follow up plugin list command is broke too it appears that it partially installed it.  In your user profile there should be a .inspec\gems\3.1.0\gems folder and you can delete the train-vmware folder out of there to fix your plugin commands I believe.

**Comment by netgurus** [comment]
OK,,that was it. Confession time. 

I had previously,,,previously tried to use Inspec 4.6.2 from the community download. When I looked at the .inpsec in my profile, there was a folder for 2.6.0 gems. Deleted the entire .inpsec, ran the repair on cinc-auditor, and wal-la. 

"train-vmware plugin, version 0.2.0, installed from local .gem file"

Thanks for the quick help. MUCH appreciated.

BTW, all the other plugins show up also.

**Comment by netgurus** [comment]
Thank you for the great support
