### ISSUE TITLE
Playbook not setting required values for VCUI-67-000025

### ISSUE THREAD

**Issue by scjohnson1988** [vmware/dod-compliance-and-automation#30]
For VCUI-67-000025, after running the command `xmllint --format /usr/lib/vmware-vsphere-ui/server/conf/web.xml | sed 's/xmlns=".*"//g' | xmllint --xpath '//param-name[text()="debug"]/parent::init-param' -` - the output returns XPath empty.

In other similar STIGs, there is a caveat that there it is not a finding if no output is returned, but that caveat does not exist for this specific STIG in V1R1.

**Comment by rlakey** [comment]
Thank you I've added that to our list of changes for the next release but yes if it doesn't exist the default is good.
