### ISSUE TITLE
"cannot load such file" when attempting to execute scan on VM

### ISSUE THREAD

**Issue by pauldglock** [vmware/dod-compliance-and-automation#34]
Receiving an error when attempting to run a scan on a VM using the VM STIG controls.
Complete details in attached file.
[error.txt](https://github.com/vmware/dod-compliance-and-automation/files/6779468/error.txt)

**Comment by rlakey** [comment]
Hey @pauldglock I've opened an issue for this on the Inspec train repo. I've worked around it from changing that line from require_relative to require but that didn't work for someone else also.

https://github.com/inspec/train/issues/693

**Comment by pauldglock** [comment]
Making that change got me further, but then another "cannot load such file" error appeared, see attached file for traceback.
[error2.txt](https://github.com/vmware/dod-compliance-and-automation/files/6823066/error2.txt)

**Comment by pauldglock** [comment]
Any status updates on this?

**Comment by rlakey** [comment]
@pauldglock I would monitor the linked inspec train issue since the resolution will come from there. 

One other note I didn't have this problem on Linux with Powershell/PowerCLI for Linux installed on 4.26.13 InSpec and the latest version.

**Comment by rlakey** [comment]
Supposed to be fixed in inspec/trail 3.8.7 now.
