### ISSUE TITLE
ESXi remediation ps1 scripts set variables at wrong moment

### ISSUE THREAD

**Issue by ed02468** [vmware/dod-compliance-and-automation#40]
I noticed that in both PowerShell scripts for the ESXi remediation (for vSphere version 6.7 and 7.0), the remediation of each vulnerability is setup the same way.
It _first_ checks if the vuln is enabled, and _then_ it initializes a few variables ($VULID, $STIGID and $Title).
This means that if the else-branch of the if-then-else is executed, that these variables are not initialized properly.
The initialization of these variables should occur _before_ the if-then branch, _not inside_ the if-then branch.

**Comment by rlakey** [comment]
Good catch we'll have to update that in the future.
