### ISSUE TITLE
VCSA 7.0 STIG - svcCfgfiles Backup Files causing Services to not start

### ISSUE THREAD

**Issue by jakevanvl** [vmware/dod-compliance-and-automation#50]
As a part of the STIGging process for VCSA7.0, backups of config files for select services are created prior to changes being made. These files are located in /etc/vmware/vmware-vmon/svcCfgfiles. When these backup files exist in the same directory as the production config files (now updated after STIGging), the services fail to start.

Specifically, affected config files are "eam.json", "lookupsvc.json", "perfcharts.json", and "vsphere-ui.json".

Remediation for this is simply making a new directory in the same folder (/etc/vmware/vmware-vmon/svcCfgfiles) named anything, and moving any .bak files to this directory. Commands are "mkdir /etc/vmware/vmware-vmon/svcCfgfiles/temp" and "mv /etc/vmware/vmware-vmon/svcCfgfiles/*.bak /etc/vmware/vmware-vmon/svcCfgfiles/temp", followed by "service-control --start all" to start affected services.

Recommend modifying the Backup file creation, to include creating a backup directory in the svcCfgfiles directory, and placing config file backups into this directory prior to restarting any services.

**Comment by HerbBoy** [comment]
Hi,

I also ran into this issue and I created a fork of this main project that has solved it.

**Comment by rlakey** [comment]
Good catch. I'll add a separate task like you did to avoid this issue for these service files but I think I'll just put them under /tmp to avoid any potential issues in that folder.
