### ISSUE TITLE
VCLU-70-000007 || Is not persistent

### ISSUE THREAD

**Issue by HerbBoy** [vmware/dod-compliance-and-automation#53]
Hi,

Vuln: VCLU-70-000007
Issue: If the lockdown is run, all the appropriate files will have the appropriate permissions applied to them. However, in the event a new file is written to this directory or sub-directory the files will come in with the improper, non-compliant permissions.

For example, I ran the lockdown of the vcenter via ansible with all successes. Rebooted the system, then ran the checker and received the following 

inSpec output: 
```
     ×  File /var/log/vmware/lookupsvc/tomcat/manager.2021-12-06.log is expected not to be more permissive than "0600"
     expected `File /var/log/vmware/lookupsvc/tomcat/manager.2021-12-06.log.more_permissive_than?("0600")` to be falsey, got true

     ×  File /var/log/vmware/lookupsvc/tomcat/host-manager.2021-12-06.log is expected not to be more permissive than "0600"
     expected `File /var/log/vmware/lookupsvc/tomcat/host-manager.2021-12-06.log.more_permissive_than?("0600")` to be falsey, got true
```

Re-ran the lockdown against this vuln id and resolved this. However this is not permanent and tomorrows files will no-longer be compliant.

**Comment by rlakey** [comment]
Thanks @HerbBoy we'll see if there's something we can figure out to update the default permissions for new log files.

**Comment by rlakey** [comment]
Yea the playbook will not resolved this but working on resolving this ootb internally with the product team.
