### ISSUE TITLE
VCUI-70-000021 || InSpec Checker Error 

### ISSUE THREAD

**Issue by HerbBoy** [vmware/dod-compliance-and-automation#55]
Hi,

Compliance Checker Control ID: VCUI-70-000021
Issue: The logic of this check does not properly validate the output of the command. This is due to the fact it is not specifying whether it wants HTTP or HTTPS.

Note: if the STIG requires both protocols be validated then two controls will need to be ran (not sure if thats the proper verbiage)

Solution:
Now the InSpec check runs:
```
  describe xml("#{input('serverXmlPath')}") do
    its(['Server/Service/Connector/@URIEncoding']) { should cmp "#{input('uriEncoding')}"}
```

and returns
```
     expected: UTF-8
          got: ["UTF-8", "UTF-8"]
```

If the command is changed with:
```
  describe xml("#{input('serverXmlPath')}") do
    its(['Server/Service/Connector[@port="${http.port}"]/@URIEncoding']) { should cmp "#{input('uriEncoding')}"}
```

the result is
```
  ✔  VCUI-70-000021: vSphere UI must set URIEncoding to UTF-8.
     ✔  XML /usr/lib/vmware-vsphere-ui/server/conf/server.xml ["Server/Service/Connector[@port=\"${http.port}\"]/@URIEncoding"] is expected to cmp == "UTF-8"
```

This has been merged into the forked branch located here: https://github.com/HerbBoy/dod-compliance-and-automation

**Comment by rlakey** [comment]
What version of vCenter are you running this against? It should only have 1 connector defined in the file I believe.

**Comment by HerbBoy** [comment]
@rlakey 
![image](https://user-images.githubusercontent.com/61263592/146625935-5f570451-0fe7-4fb7-be08-58a7a003d396.png)


I just built out this vCenter 13 days ago.
