### ISSUE TITLE
remove the wrappers directory and just move the inspec.yml, controls dir and such up a level

### ISSUE THREAD

**Issue by aaronlippold** [vmware/dod-compliance-and-automation#6]
To keep more in line with a starndard wrapper profile - actually having a 'wrapper' profile is not really needed the 'profile' itself is the wrapper

**Comment by aaronlippold** [comment]
https://github.com/vmware/dod-compliance-and-automation/tree/master/vsphere/6.7/vcsa/inspec/vmware-vcsa-6.7-stig-baseline/wrapper

is overly specific

**Comment by rlakey** [comment]
More like this one Aaron?

https://github.com/vmware/dod-compliance-and-automation/tree/master/vsphere/7.0/vcsa/inspec/vmware-vcsa-7.0-stig-baseline

**Comment by rlakey** [comment]
Fixed in linked pull request.
