### ISSUE TITLE
PowerShell Remediation Scripts || Do not work on PowerShell Core

### ISSUE THREAD

**Issue by HerbBoy** [vmware/dod-compliance-and-automation#63]
Hi,

Issue: The PowerShell remediation scripts do not work if ran from a linux box running powershell core. See image below

![image](https://user-images.githubusercontent.com/61263592/145248514-5092d8b4-8d83-412d-a8ed-e49eac832104.png)

Solution: Leverage Ansible for ESXi and VM Lockdown.

Currently working on ESXi ansible lockdown on the forked branch located: https://github.com/HerbBoy/dod-compliance-and-automation

**Comment by HerbBoy** [comment]
ESXI lockdown is complete

**Comment by HerbBoy** [comment]
VM Lockdown is complete and can be found in my forked branch

**Comment by rlakey** [comment]
This one was recently fixed so you may have had a copy before I updated this one.

See: https://github.com/vmware/dod-compliance-and-automation/commit/471aa44c359fb8d276eafc8c0e7d944c60da7be7

**Comment by HerbBoy** [comment]
The ansible roles I created do lockdown more then previous powershell did - it would also be nice to implement both options giving users the ability to run ansible over ps scripts
