### ISSUE TITLE
ESXI-70-000083 | is not a installed service

### ISSUE THREAD

**Issue by HerbBoy** [vmware/dod-compliance-and-automation#66]
## Issue ## 
Compliance check for ** ESXI-70-000083 ** fails due to the service not having a rule listed of "off" or "not-running".

```
×  ESXI-70-000083: The ESXi host OpenSLP service must be disabled. (2 failed)
     ×  PowerCLI Command: (Get-VMHost -Name 192.168.0.14) | Get-VMHostService | Where {$_.Label -eq 'slpd'} | Select-Object -ExpandProperty Policy stdout.strip is expected to cmp == "off"

     expected: off
          got:

     (compared using `cmp` matcher)

     ×  PowerCLI Command: (Get-VMHost -Name 192.168.0.14) | Get-VMHostService | Where {$_.Label -eq 'slpd'} | Select-Object -ExpandProperty Running stdout.strip is expected to cmp == "false"

     expected: false
          got:

     (compared using `cmp` matcher)
```

## Solution ##
Check if service is installed/present if it is not, then this is not a finding.

```
  list1 = ["","off"]
  command = "(Get-VMHost -Name #{input('vmhostName')}) | Get-VMHostService | Where {$_.Label -eq 'ESXi Shell'} | Select-Object -ExpandProperty Policy"
  describe powercli_command(command) do
    its ('stdout.strip') { should be_in list1 }
  end

  list2 = ["","false"]
  command = "(Get-VMHost -Name #{input('vmhostName')}) | Get-VMHostService | Where {$_.Label -eq 'slpd'} | Select-Object -ExpandProperty Running"
  describe powercli_command(command) do
    its ('stdout.strip') { should be_in list2 }
  end
```

**Comment by rlakey** [comment]
@HerbBoy What version of ESXi/PowerCLI are you running this against? I'm not seeing this behavior in the any 7.0 versions i've tried.

**Comment by HerbBoy** [comment]
@rlakey 

ESXi:
ESXi:
![image](https://user-images.githubusercontent.com/61263592/146625967-fc59faba-4145-4fc4-9b48-6ce7f22724d8.png)

PowerCLI:
![image](https://user-images.githubusercontent.com/61263592/146625983-d106e3df-c041-4d04-8a72-1ce3eae0704c.png)\

PowerCLI I pulled the package 13 days ago.

I believe these are the latest versions however I could be wrong. I am running everything from a RHEL 8 host, running Powershell Core with PowerCLI installed.

not running any of this from a windows host as it is not an option in my use case.

**Comment by rlakey** [comment]
Ok I see the issue. Apparently this service was exposed through the UI and PowerCLI in a later version of 7.0 but still exists in 6.7/7.0 as you can see here: https://kb.vmware.com/s/article/76372

The ESXi version you are running is the GA version and should be upgraded. You can see a list of build numbers for 7.0 here: https://kb.vmware.com/s/article/2143832
