### ISSUE TITLE
VMCH-70-000012 | InSpec Compliance Check Logic Error

### ISSUE THREAD

**Issue by HerbBoy** [vmware/dod-compliance-and-automation#67]
### Describe the bug

The logic of this check does not properly check if there is a USB device attached to a given vm.

Example output of the command ran:
```
IDE 0
IDE 1
PS2 controller 0
PCI controller 0
SIO controller 0
Keyboard
Pointing device
Video card
VMCI device
USB controller
SCSI controller 0
CD/DVD drive 1
Hard disk 1
Network adapter 1
Audio
```

### Reproduction steps

```bash
1. inspec exec vmware-vsphere-vm-7.0-stig-baseline -t vmware:// --input vm_name_here --show-progress --reporter=cli json:out_put_file_location_here --controls=VMCH-70-000012
...
```

### Expected behavior

The expected behavior of this check is to ensure no USB devices are connected to a given VM. Therefore this is solved like so:

```
command = "$usb_controller_check = (Get-VM -Name #{input('vmName')}).ExtensionData.Config.Hardware.Device.DeviceInfo.label -match \"usb\"; if($usb_controller_check -match \"USB controller\"){Get-VM -Name #{input('vmName')} | Get-UsbDevice}"
  describe powercli_command(command) do
    its ('stdout') { should_not match 'USB' }
    its ('exit_status') { should cmp 0 }
  end

end
```

This will adequetely check if a USB controller exists and then see if a USB device is connected to the given VM.

### Additional context

This will be solved and implemented in my forked branch.

**Comment by rlakey** [comment]
What was the output you were seeing before you made your changes? I wasn't able to reproduce this as it was written.

Below is my output from a VM with a USB device then one without and it fails and passes as expected.

Profile: vSphere 7.0 Virtual Machine STIG Profile (vSphere 7.0 Virtual Machine STIG Profile)

  ×  VMCH-70-000012: Unauthorized USB devices must be disconnected on the virtual machine. (1 failed)
     ×  PowerCLI Command: (Get-VM -Name test).ExtensionData.Config.Hardware.Device.DeviceInfo.label stdout is expected not to match "USB"
     expected "IDE 0\nIDE 1\nPS2 controller 0\nPCI controller 0\nSIO controller 0\nKeyboard \nPointing device\nVide...controller \nSCSI controller 0\nSATA controller 0\nCD/DVD drive 1\nHard disk 1\nNetwork adapter 1\n" not to match "USB"
     Diff:
     @@ -1,2 +1,16 @@
     -USB
     +IDE 0
     +IDE 1
     +PS2 controller 0
     +PCI controller 0
     +SIO controller 0
     +Keyboard
     +Pointing device
     +Video card
     +VMCI device
     +USB xHCI controller
     +SCSI controller 0
     +SATA controller 0
     +CD/DVD drive 1
     +Hard disk 1
     +Network adapter 1

     ✔  PowerCLI Command: (Get-VM -Name test).ExtensionData.Config.Hardware.Device.DeviceInfo.label exit_status is expected to cmp == 0


Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
Test Summary: 1 successful, 1 failure, 0 skipped





Profile: vSphere 7.0 Virtual Machine STIG Profile (vSphere 7.0 Virtual Machine STIG Profile)

  ✔  VMCH-70-000012: Unauthorized USB devices must be disconnected on the virtual machine.
     ✔  PowerCLI Command: (Get-VM -Name test).ExtensionData.Config.Hardware.Device.DeviceInfo.label stdout is expected not to match "USB"
     ✔  PowerCLI Command: (Get-VM -Name test).ExtensionData.Config.Hardware.Device.DeviceInfo.label exit_status is expected to cmp == 0


Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 2 successful, 0 failures, 0 skipped

**Comment by rlakey** [comment]
I see what you were trying to do but the control fails if a controller exists and that has to exist for a USB device to exist so I just check for that.

Also I think yours as written will fail if a USB 3.0 since there are two types with different names.

USB xHCI controller
USB controller

**Comment by HerbBoy** [comment]
@rlakey 

I guess im just used to Ansible where a fail is not a good thing. That said, the issue you point out can be solved by telling it about both USB types?
