### ISSUE TITLE
Ansible alternative to PowerShell Lockdown for ESXi and VMs

### ISSUE THREAD

**Issue by HerbBoy** [vmware/dod-compliance-and-automation#69]
### Is your feature request related to a problem? Please describe.

I did encounter an issue that had been apparently resolved. That said I believe Ansible presents a better path forward then PowerShell Scripts.

### Describe the solution you'd like

In a fork of this project I built out both the ESXi and VM Ansible lockdowns.

https://github.com/HerbBoy/dod-compliance-and-automation

### Additional context

PowerShell Scripts to me are the same as running Bash scripts. They work, but are they the best approach?

Ansible provides idempotency. In the Ansible roles i developed to lockdown ESXi and VM's leverage both shell (non-idempotent by default) and Ansible modules that are idempotent. Therefore, this enables the ability to re-run the same role over and over but if no changes are necessary then no changes are made.

Throughout building out these two roles I was also able to lockdown more then the previous PowerShell scripts were.

**Comment by rlakey** [comment]
@HerbBoy If you want to submit a PR for the role created we can get it added to the repo.

**Comment by pstearns** [comment]
@HerbBoy We were following your ansible for ESXi solution, and it looked promising. Your fork no longer contains them after the latest sync, would it be possible to readd them?

**Comment by HerbBoy** [comment]
@pstearns I am in the process of using the latest content from the repo to submit a MR/PR to this repo so that I can help to maintain or atleast provide an ansible solution for those with a desire for more ansible and less PS.

**Comment by HerbBoy** [comment]
@pstearns checkout #110

**Comment by pstearns** [comment]
@HerbBoy Awesome, I will start looking at these next week. Thanks for working on these.

**Comment by HerbBoy** [comment]
sounds good. the plan is to continue to further automate away from the few powershell commands being used but based on my time researching, vmware APIs and vmware modules are not able to do everything PowerCLI is for some reason

**Comment by rlakey** [comment]
I think we can close this since the playbooks submitted for this have been merged.
