### ISSUE TITLE
Private, licensed container image from VMware for CI/CD testing of PowerShell Scripts

### ISSUE THREAD

**Issue by potatoqualitee** [vmware/dod-compliance-and-automation#70]
### Is your feature request related to a problem? Please describe.

GitHub Actions and the GitHub Container Registry potentially provide the necessary foundation for VMware to create a container that we can test our scripts against.

With many of my PowerShell projects, I create Integration tests and run live code against a live web server, as seen in my workflow for tentools, which tests PowerShell commands against a live Nessus instance https://github.com/potatoqualitee/tentools/blob/main/.github/workflows/main.yml

It would be great to have this option to test the PowerShell commands found in this repo using Pester, which is built into all GitHub Runners. The downside is that vSphere does take like 20 minutes to start up, so each run would take at least that amount of time. Also, I'm not sure if PowerCLI is Core Compatible yet.

### Describe the solution you'd like

Full on CI/CD solution for the PowerShell scripts within this repo.

### Describe alternatives you've considered

ESX does boot up a bit faster, so perhaps initially limit the scope to ESX and the vmware fling.

**Comment by rlakey** [comment]
Sounds like a good idea @potatoqualitee. We'll see if we can carve out some time for it.

PowerCLI works on Powershell Core too.

**Comment by potatoqualitee** [comment]
I've been trying to figure this out and concluded:

* Oh, oops. ESX can't run on the Ubuntu runner
* Also, even if we could, starting it up from scratch would take less than 60 minutes, sure, but longer than 5, which would get frustrating

I [created a PR](https://github.com/vmware/dod-compliance-and-automation/pull/81) with linting tests but really love/prefer Integration tests and was trying to work towards that.

My guess is that the only way to do this is to create an ESX machine in Azure (or AWS but I'm most familiar with Azure) and have the tests run against that. The upside would be that it's already running and inspec doesn't make changes, so the tests would be predictable.

The downside is that you have to enable access to this VM to GitHub Runners. I do similar things in [my own repo](https://github.com/dataplat/dbatools) with an isolated subscription that's basically dedicated to tests.

Within SQL Server in Azure, setting "Allow Azure services and resources to access this server" to Yes allows all GitHub Actions runners to connect to Azure SQL Server. Perhaps there is a similar setting for VMs and VNETs?

![image](https://user-images.githubusercontent.com/8278033/159116550-d70c9532-18b9-4f9f-b272-3d1a0a9851da.png)

If not,perhaps this can be used

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#ip-addresses-of-runners-on-github-hosted-machines
