### ISSUE TITLE
ETA of Official STIG Release

### ISSUE THREAD

**Issue by HerbBoy** [vmware/dod-compliance-and-automation#73]
### Is your feature request related to a problem? Please describe.

This is not really a feature but its the only two options available.

As someone that has to implement and apply DoD STIG's against applicable systems I am required to use officially released STIG's from DISA.

Currently there is not 7.0 stig for the VMware suite as there is in this repo. Which leads me to this question, when is 7.0 officially going to be released? 

And when i say STIG i mean as seen here: https://public.cyber.mil/stigs/downloads/ then search vmware

### Describe the solution you'd like

n/a

**Comment by HerbBoy** [comment]
@freddyfeelgood @rlakey tagging you both as you are the ones ive interacted with on the vmware side

**Comment by rlakey** [comment]
Hi since we are not in control of the project or timelines you would have to reach out to DISA for specifics but we have made the content available to them and here to bridge the gap between development and publication.

**Comment by HerbBoy** [comment]
thank you for the information
