### ISSUE TITLE
vmware.rb cannot load such file

### ISSUE THREAD

**Issue by potatoqualitee** [vmware/dod-compliance-and-automation#74]
### Describe the bug

I tried running `C:\opscode\inspec\bin\inspec.bat exec C:\Inspec\Profiles\vmware-vsphere-vcenter-7.0-stig-baseline -t vmware://` in PowerShell 5.1 on Windows 11, as described in the docs, with no luck. I installed Chef Inspec today, with the latest version. There appears to be an issue with a `vmware.rb` file.

### Reproduction steps

```bash
C:\opscode\inspec\bin\inspec.bat  exec C:\Inspec\Profiles\vmware-vsphere-vcenter-7.0-stig-baseline -t vmware://
```

Which produces the following fault

```bash
Traceback (most recent call last):
        16: from C:/opscode/inspec/bin/inspec:301:in `<main>'
        15: from C:/opscode/inspec/bin/inspec:301:in `load'
        14: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-4.52.9/bin/inspec:11:in `<top (required)>'
        13: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/base_cli.rb:35:in `start'
        12: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        11: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        10: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
         9: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
         8: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/cli.rb:301:in `exec'
         7: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/cli.rb:301:in `new'
         6: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/runner.rb:79:in `initialize'
         5: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/runner.rb:87:in `configure_transport'
         4: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/backend.rb:38:in `create'
         3: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-3.8.6/lib/train/transports/vmware.rb:16:in `connection'
         2: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-3.8.6/lib/train/transports/vmware.rb:16:in `new'
         1: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-3.8.6/lib/train/transports/vmware.rb:37:in `initialize'
C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-3.8.6/lib/train/transports/vmware.rb:37:in `require_relative': cannot load such file -- C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-3.8.6/lib/train/transports/local (LoadError)
```

### Expected behavior

The command works without an exception being thrown

**Comment by HerbBoy** [comment]
@potatoqualitee

I did test on a windows box and received the same error. However, to me this error shows it to be a InSpec error as the vmware.rb is not a product of this repository and is managed by the InSpec Train project (https://github.com/inspec/train)

That said, if you need to get up and running you can do so via a linux box (only done so via a VM - but id take a guess and say WSL would also work.)

I use a RHEL 8 box to run InSpec with the required dependencies installed.

Hope this helps steer you in the right direction.

**Comment by potatoqualitee** [comment]
That helps a lot, @HerbBoy! Thank you. I wondered if Linux was the interim solution. I'll file an issue with inspec/train. Thanks again

**Comment by rlakey** [comment]
See https://github.com/inspec/train/issues/693

Supposedly a fix was just released and in inspec/train 3.8.7 but I haven't had a chance to test it yet. I see you were on 3.8.6.

**Comment by potatoqualitee** [comment]
Thank you @rlakey! I'm not familiar with ipsec at all -- this is my first use of it. I see that inspec's Windows isntaller from their website is still the same version, so I'll have to update train manually. I'll delete my old train directory, download their release from GitHub then expand the directory within the appropriate opscode directory and give it a go 🤞🏼

**Comment by potatoqualitee** [comment]
LOL I got it to work, but it was not pretty. I downloaded train's latest release then extracted the lib directory and saved it to

`C:\opscode\inspec\embedded\lib\ruby\gems\2.7.0\gems\train-3.8.6`
`C:\opscode\inspec\embedded\lib\ruby\gems\2.7.0\gems\train-core-3.8.6`

So the version suggested by the directory is no longer accurate, but it works! Progress.

![image](https://user-images.githubusercontent.com/8278033/152833022-1479484e-5be2-44ba-86ce-6ee9e08a8e8d.png)

Now to figure out how to do this properly while emulating an offline environment 😅
