### ISSUE TITLE
How does the powercli_command.rb check for PowerCLI

### ISSUE THREAD

**Issue by HerbBoy** [vmware/dod-compliance-and-automation#80]
### Describe the bug

PowerCLI Version: [12.5.0.19195797](https://www.powershellgallery.com/packages/VMware.PowerCLI/12.5.0.19195797)
OS: RHEL 8.4
PowerShell Core Version: 7.2.1-1.rh

This appeared in an offline, highside env. All dependencies already present (inspec, powershell core).

I first tried to import the library.

```
Import-Module vmware.powercli
...
Exception: The VMware.ImageBuilder module is not currently supported on the Core edition of PowerShell.
```
After that did not work, I just copied over the structure and placed the VMware.PowerCLI and all its dependencies into /root/.local/share/powershell/Modules/

After I did that I was able to run PowerCLI commands. Connect to a server etc.

However I get the following error from InSpec

```
Unable to determine PowerCLI Module version, is it installed?
```

At that point I tried to dig through some stuff but at this point I am unsure if this is the right repo/project to post this in but https://github.com/chef-boneyard/inspec-vmware is not active.

I just need to find where it is checking for PowerCLI then i can modify the logic but I dont know where its checking for that.

### Reproduction steps

```bash
1. Offline Environment with no access to a PowerShell Repository (PowerShell Core
2. Bring over the PowerCLI Modules and place into /root/.local/share/powershell/Modules/
3. Run a Connect-VIServer or whatever command to validate it is installed
4. Run ESXi InSpec Profile
```

### Expected behavior

For it to work as it does on Internet connected devices. 

When i did testing and dev in a environment that had internet, and packages could be pulled directly from powershell gallery this was not an issue.

### Additional context

Again, this may be the wrong project/repo to be positing this issue.

**Comment by HerbBoy** [comment]
Found where the logic was called.

Will test my changes then document and share.

**Comment by HerbBoy** [comment]
This is a bug with the InSpec Train for non-imported or installed modules.

I will be writing an issue there.

**Comment by HerbBoy** [comment]
If interested https://github.com/inspec/train/issues/725

**Comment by rlakey** [comment]
The Import-Module should work with the exception of that one piece of it that generates that message. Did that message actually stop you from running cmdlets? Not sure why it's listed as an exception and not a warning.

**Comment by HerbBoy** [comment]
@rlakey 

Yeah it sends the exception message and even then I tried to run the InSpec tool with the same results.

I am farily certain/confident the way transport validates its installed would not always work.

As when i do this with Install-Module it works without issue.
