### ISSUE TITLE
PHTN-30-000055 || VCSA 7.0 Ansible adds duplicate

### ISSUE THREAD

**Issue by gkearchn** [vmware/dod-compliance-and-automation#84]
### Describe the bug

When running the "PHTN-30-000055 - Configure auditd num_logs" task, Ansible adds the num_logs = 5 line to the end of the '/etc/audit/auditd.conf' file. When the task was run the file already had the entry of num_logs = 2 but this was not removed/edited therefor I end up having 2 entries for num_logs.

It looks like the logic below is looking for the exact match of num_logs = 5 but not taking into account other values. I am not strong with Ansible but it seems like an easy enough adjustment and there may be other tasks which could face a similar problem. Thanks.

- name: PHTN-30-000055 - Configure auditd num_logs
  lineinfile:
    dest: '{{ var_auditd_conf_file }}'
    line: num_logs = {{ var_auditd_num_logs }}
    state: present
  tags:
  - PHTN-30-000055
  - auditd
  notify:
  - restart auditd
  when:
  - run_auditd_num_logs | bool

### Reproduction steps

```bash
Run the "PHTN-30-000055 - Configure auditd num_logs" task and make sure the num_logs = somthing other than 5 in the '/etc/audit/auditd.conf' file.
```

### Expected behavior

The task does what it should but I would expect it to check for all values of num_logs and replace with num_logs = 5.

**Comment by rlakey** [comment]
Thanks for the report. We'll take a look at this.
