### ISSUE TITLE
VCSA sshd does not start after applying Photon3 STIG role

### ISSUE THREAD

**Issue by Aggraxis** [vmware/dod-compliance-and-automation#86]
### Describe the bug

Could not SSH into our VCSA (installed from 7.0.3 install ISO, 19480866) after running the Photon3 role against the appliance. `systemctl status sshd.service` reported failure to start. Running `sshd -t`  yielded the message "FipsMode should be set before Ciphers option". It appears that the playbook is configured to deal with these two configuration parameters being in the proper sequence, but we found that the original sshd_config had two instances of FipsMode in it, leading to the issue.

Original config:

```
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

FipsMode yes       <---FIRST INSTANCE

# no default banner path
Banner /etc/issue

# override default of no subsystems
Subsystem       sftp    /usr/libexec/sftp-server

# Example of overriding settings on a per-user basis
#Match User anoncvs
#       X11Forwarding no
#       AllowTcpForwarding no
#       PermitTTY no
#       ForceCommand cvs server
AllowTcpForwarding no
ClientAliveCountMax 0
Compression no
MaxAuthTries 2
TCPKeepAlive no
AllowAgentForwarding no
PermitRootLogin yes
UsePAM yes
SyslogFacility AUTHPRIV
LogLevel INFO
FipsMode yes         <---SECOND INSTANCE
GSSAPIAuthentication no


```

Post-playbook:

```
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

FipsMode yes    <---- FIRST INSTANCE
Ciphers aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

# no default banner path
Banner /etc/issue

# override default of no subsystems
Subsystem       sftp    /usr/libexec/sftp-server

# Example of overriding settings on a per-user basis
#Match User anoncvs
#       X11Forwarding no
#       AllowTcpForwarding no
#       PermitTTY no
#       ForceCommand cvs server
AllowTcpForwarding no
ClientAliveCountMax 0
Compression no
MaxAuthTries 6
TCPKeepAlive no
AllowAgentForwarding no
PermitRootLogin yes
UsePAM yes
SyslogFacility AUTHPRIV
LogLevel INFO
#FipsMode yes     <---- SECOND INSTANCE, manually commented out to get sshd started
GSSAPIAuthentication no


```

We dug around in the system and realized that the 7.0u3 install may have two instances of FipsMode in the config. This playbook pounces on the first instance, then inserts the ciphers line right after it. 

### Reproduction steps

```bash
1. Installed VCSA 7.0.3 (we performed an upgrade from the latest 6.7 appliance, which previously had the 6.7 STIG role run against it)
2. Run Photon3 STIG role
3. Reboot
4. SSH fails to connect, config has two FipsMode lines in it, one after the ciphers line and causing the service to fail on start.
```

### Expected behavior

SSH should still work post-playbook. It looks like there are two instances of the FipsMode entry in the default config. Either pruning one of the lines out of the config or changing the task to get the last match instead of the first match when seeking for ^FipsMode.  I manually applied both changes independently, and both version of the config pass a sshd -t validation just fine.

**Comment by rlakey** [comment]
Yea I noticed this issue recently as well and for now I am documenting it as a known issue with the vCenter playbook consuming the Photon playbook since it's not really a Photon playbook issue since this second option shouldn't be there and OpenSSH shouldn't allow duplicate configurations either.

Updated playbooks with this documented will be posted soon.
