### ISSUE TITLE
Add vcenter appliance-isms to photon3 role or supply them in a supplementary role in the vcenter content

### ISSUE THREAD

**Issue by Aggraxis** [vmware/dod-compliance-and-automation#89]
### Is your feature request related to a problem? Please describe.

Some of the photon3 controls do not persist after a reboot. The controls that pertain to /etc/pam.d/system-password, for example, were all reset to their pre-playbook values after we rebooted our appliance.

### Describe the solution you'd like

The controls that pertain to /etc/pam.d/system-password contain a note in the STIG calling out a need to edit the equivalent file under /etc/applmgmt/appliance for the changes to persist after a reboot. It would be convenient to have either tasks in the photon3 role or a supplementary set of tasks in the vcsa ansible content that did something like the following:
```
Check to see if we're a vCenter appliance (maybe look to see if /etc/applmgmt/equivalent_file exists)
If so, make the changes there as well.
If not, move on.
```

V1R4 of the Photon OS STIG has 12 Rule IDs where /etc/applmgmt/appliance matches a keyword filter:

- SV-PHTN-30-000002
- SV-PHTN-30-000021
- SV-PHTN-30-000022
- SV-PHTN-30-000023
- SV-PHTN-30-000024
- SV-PHTN-30-000029
- SV-PHTN-30-000030
- SV-PHTN-30-000050
- SV-PHTN-30-000071
- SV-PHTN-30-000073
- SV-PHTN-30-000110
- SV-PHTN-30-000117

Thank you!

**Comment by rlakey** [comment]
Hi @Aggraxis this is taken care of in the vcsa profile here: https://github.com/vmware/dod-compliance-and-automation/blob/master/vsphere/7.0/vcsa/ansible/vmware-vcsa-7.0-stig-ansible-hardening/roles/misc/tasks/misc.yml

My intention is for a product specific profile to consume the photon content and make any adjustments as part of the product playbook/profile. InSpec lets us do this via including the photon role and excluding certain controls or through a waivers file if there are controls that aren't applicable to say vCenter.

For Ansible I'm doing this most through vars specified on the photon role being imported in the product specific playbook. This particular scenario was a bit of an outlier so i added the misc task to handle it.

**Comment by Aggraxis** [comment]
I totally missed it. When we cloned yesterday's update we noticed that all of the playbooks were written for the newer Ansible. We're still waiting on our tower licenses to go through contracting before we upgrade our local instance. But yeah, this one caught my eye because of it being an outlier, like you said. Thank you for taking the time to respond!

**Comment by rlakey** [comment]
No problem!
