### ISSUE TITLE
VMCH-70-000026 Calling wrong key value for issue

### ISSUE THREAD

**Issue by cdepierro-bsky** [vmware/dod-compliance-and-automation#92]
### Describe the bug

VMCH-70-000026 

The script for this control is calling key vmx.log.rotateSize which will fail. Correct key should be log.rotateSize

### Reproduction steps

```bash
1.  [FAIL]  VMCH-70-000026: Log size must be properly configured on the virtual machine. (1 failed)
     [FAIL]  PowerCLI Command: (Get-VM -Name groundstation.cju.gemini | Get-AdvancedSetting -Name vmx.log.rotateSize).value stdout.strip is expected to cmp == "2048000"

     expected: 2048000
          got:

2. Changing vmx.log.rotateSize to log.rotateSize passes

  [PASS]  VMCH-70-000026: Log size must be properly configured on the virtual machine.
     [PASS]  PowerCLI Command: (Get-VM -Name groundstation.cju.gemini | Get-AdvancedSetting -Name log.rotateSize).value stdout.strip is expected to cmp == "2048000"
     [PASS]  PowerCLI Command: (Get-VM -Name groundstation.cju.gemini | Get-AdvancedSetting -Name log.rotateSize).value exit_status is expected to cmp == 0

3.
...
```

### Expected behavior

Expected this to pass when pulling the correct key for the VM
  [PASS]  VMCH-70-000026: Log size must be properly configured on the virtual machine.
     [PASS]  PowerCLI Command: (Get-VM -Name groundstation.cju.gemini | Get-AdvancedSetting -Name log.rotateSize).value stdout.strip is expected to cmp == "2048000"
     [PASS]  PowerCLI Command: (Get-VM -Name groundstation.cju.gemini | Get-AdvancedSetting -Name log.rotateSize).value exit_status is expected to cmp == 0

**Comment by cdepierro-bsky** [comment]
Also Same applies for VMCH-70-000027 with vmx.log.keepOld needs to be changed to log.keepOld

**Comment by rlakey** [comment]
Looks like this was already addressed. Please reopen if found in the latest branch.
