### ISSUE TITLE
Advanced Settings failing in vSphere 7.0U3d?!

### ISSUE THREAD

**Issue by ed02468** [vmware/dod-compliance-and-automation#94]
### Describe the bug

I noticed that when the PowerCLI script sets advanced parameters on the Virtual Machines, they now fail.
It failed for me in 7.0U3d, while it works fine in 7.0U2d.

I [brought this up in the PowerCLI community](https://communities.vmware.com/t5/VMware-PowerCLI-Discussions/Cannot-add-an-advanced-parameter-to-VM-when-powered-on-in-7-0U3d/m-p/2913557) and got the following feedback (from LucD): "This just looks like they closed a backdoor, and forgot to update some documentation that referred to that backdoor."

### Reproduction steps

```bash
Run the remediation script for VMs (VMware_vSphere_7.0_STIG_VM_Remediation-VxRail_STIG.ps1) on vSphere 7.0U3d, 
OR simply:
1. Open a PowerShell window
2. Connect to vCenter on vSphere 7.0U3d (Connect-VIServer)
2. Get the VM object (I tested with the VCSA VM)
3. Add an advanced parameter to the VM ($vm | New-AdvancedSetting ...)
```

### Expected behavior

The advanced parameter gets successfully added to the VM configuration.

**Comment by rlakey** [comment]
Hi @ed02468 I still haven't been able to track down under which scenarios this is happening.  It's worked for me on newer versions so maybe the PowerCLI version also plays a role here as well?  What version of PowerCLI were you on?

**Comment by ed02468** [comment]
Hi @rlakey I just checked and we are using **PowerCLI version 12.5**, working on **vSphere 7.0U3d**. 
Were you using PCLI 12.6? I see in the PowerShell Gallery that that came out 4 months ago?

**Comment by rlakey** [comment]
I believe so.  I am on 12.7 now but seeing it looks like it's depedent on the setting you are trying to set.  The isolation ones exhibit this behavior but some others do not.

**Comment by ed02468** [comment]
Ok, thanks. So that means those require a shutdown now. I have started to include that in my code. 👍
