### ISSUE TITLE
Photon playbook: No action detected in task

### ISSUE THREAD

**Issue by potatoqualitee** [vmware/dod-compliance-and-automation#96]
### Describe the bug

When running the photon playbook (downloaded from the repo today), I encounter errors

```
ERROR! No action detected in task. This often indicates a misspelled module name or incorrect module path

This error appears to be in /tmp/vmare-photon-3.0-stig-ansible-hardening/roles/photon3/tasks/photon.yml line 113, column 3 but may be elsewhere.

-name: PHTN-30-0000002 Delete rule for pam_tally2.so if it doesn't exist after the pam_unix.so auth rule in system-auth
```

When I deleted that whole block, it moved on to erroring on 00000003

I was able to run the playbook from back in March successfully 

### Reproduction steps

```bash
1. cd vmware-photon-3.0-stig-ansible-hardening
2. ansible-playbook -i 'localhost', -u 'root' playbook.yml -k -v
3. Successfully authenticate
```

### Expected behavior

It works

### Additional context

ansible 2.8.18
python version 3.7.5

(included in vcsa)

**Comment by rlakey** [comment]
This may just be an issue running the newer playbook with an older version of ansible. I run these from a system other than vCenter and am connecting to it remotely when running the playbook.

**Comment by potatoqualitee** [comment]
ahh i was concerned that may be the problem :/ im using the anisble included in vCenter so hopefully they update it soon.
